import pandas as pd
import re
from typing import Dict, List, Set, Tuple

# NSE500 company data as a dictionary for quick lookup
NSE500_COMPANIES = {
    '360 ONE WAM': '360ONE',
    '3M INDIA': '3MINDIA',
    'ABB INDIA': 'ABB',
    'ACC': 'ACC',
    'ACME SOLAR': 'ACMESOLAR',
    'AIA ENGINEERING': 'AIAENG',
    'APL APOLLO': 'APLAPOLLO',
    'AU SMALL FINANCE BANK': 'AUBANK',
    'AWL': 'AWL',
    'AADHAR HOUSING': 'AADHARHFC',
    'AARTI INDUSTRIES': 'AARTIIND',
    'AAVAS': 'AAVAS',
    'ABBOTT INDIA': 'ABBOTINDIA',
    'ACE': 'ACE',
    'ADANI ENERGY': 'ADANIENSOL',
    'ADANI ENTERPRISES': 'ADANIENT',
    'ADANI GREEN': 'ADANIGREEN',
    'ADANI PORTS': 'ADANIPORTS',
    'ADANI POWER': 'ADANIPOWER',
    'ADANI TOTAL GAS': 'ATGL',
    'ABCAPITAL': 'ABCAPITAL',
    'ABFRL': 'ABFRL',
    'ABREL': 'ABREL',
    'ABSLAMC': 'ABSLAMC',
    'AEGIS LOG': 'AEGISLOG',
    'AFCONS': 'AFCONS',
    'AFFLE': 'AFFLE',
    'AJANTPHARM': 'AJANTPHARM',
    'AKUMS': 'AKUMS',
    'APLLTD': 'APLLTD',
    'ALIVUS': 'ALIVUS',
    'ALKEM': 'ALKEM',
    'ALKYLAMINE': 'ALKYLAMINE',
    'ALOKINDS': 'ALOKINDS',
    'ARE&M': 'ARE&M',
    'AMBER': 'AMBER',
    'AMBUJACEM': 'AMBUJACEM',
    'ANANDRATHI': 'ANANDRATHI',
    'ANANTRAJ': 'ANANTRAJ',
    'ANGELONE': 'ANGELONE',
    'APARINDS': 'APARINDS',
    'APOLLOHOSP': 'APOLLOHOSP',
    'APOLLOTYRE': 'APOLLOTYRE',
    'APTUS': 'APTUS',
    'ASAHIINDIA': 'ASAHIINDIA',
    'ASHOKLEY': 'ASHOKLEY',
    'ASIANPAINT': 'ASIANPAINT',
    'ASTERDM': 'ASTERDM',
    'ASTRAZEN': 'ASTRAZEN',
    'ASTRAL': 'ASTRAL',
    'ATUL': 'ATUL',
    'AUROPHARMA': 'AUROPHARMA',
    'AIIL': 'AIIL',
    'DMART': 'DMART',
    'AXISBANK': 'AXISBANK',
    'BASF': 'BASF',
    'BEML': 'BEML',
    'BLS': 'BLS',
    'BSE': 'BSE',
    'BAJAJ-AUTO': 'BAJAJ-AUTO',
    'BAJFINANCE': 'BAJFINANCE',
    'BAJAJFINSV': 'BAJAJFINSV',
    'BAJAJHLDNG': 'BAJAJHLDNG',
    'BAJAJHFL': 'BAJAJHFL',
    'BALKRISIND': 'BALKRISIND',
    'BALRAMCHIN': 'BALRAMCHIN',
    'BANDHANBNK': 'BANDHANBNK',
    'BANKBARODA': 'BANKBARODA',
    'BANKINDIA': 'BANKINDIA',
    'MAHABANK': 'MAHABANK',
    'BATAINDIA': 'BATAINDIA',
    'BAYERCROP': 'BAYERCROP',
    'BERGEPAINT': 'BERGEPAINT',
    'BDL': 'BDL',
    'BEL': 'BEL',
    'BHARATFORG': 'BHARATFORG',
    'BHEL': 'BHEL',
    'BPCL': 'BPCL',
    'BHARTIARTL': 'BHARTIARTL',
    'BHARTIHEXA': 'BHARTIHEXA',
    'BIKAJI': 'BIKAJI',
    'BIOCON': 'BIOCON',
    'BSOFT': 'BSOFT',
    'BLUEDART': 'BLUEDART',
    'BLUESTARCO': 'BLUESTARCO',
    'BBTC': 'BBTC',
    'BOSCHLTD': 'BOSCHLTD',
    'FIRSTCRY': 'FIRSTCRY',
    'BRIGADE': 'BRIGADE',
    'BRITANNIA': 'BRITANNIA',
    'MAPMYINDIA': 'MAPMYINDIA',
    'CCL': 'CCL',
    'CESC': 'CESC',
    'CGPOWER': 'CGPOWER',
    'CRISIL': 'CRISIL',
    'CAMPUS': 'CAMPUS',
    'CANFINHOME': 'CANFINHOME',
    'CANBK': 'CANBK',
    'CAPLIPOINT': 'CAPLIPOINT',
    'CGCL': 'CGCL',
    'CARBORUNIV': 'CARBORUNIV',
    'CASTROLIND': 'CASTROLIND',
    'CEATLTD': 'CEATLTD',
    'CENTRALBK': 'CENTRALBK',
    'CDSL': 'CDSL',
    'CENTURYPLY': 'CENTURYPLY',
    'CERA': 'CERA',
    'CHALET': 'CHALET',
    'CHAMBLFERT': 'CHAMBLFERT',
    'CHENNPETRO': 'CHENNPETRO',
    'CHOLAHLDNG': 'CHOLAHLDNG',
    'CHOLAFIN': 'CHOLAFIN',
    'CIPLA': 'CIPLA',
    'CUB': 'CUB',
    'CLEAN': 'CLEAN',
    'COALINDIA': 'COALINDIA',
    'COCHINSHIP': 'COCHINSHIP',
    'COFORGE': 'COFORGE',
    'COLPAL': 'COLPAL',
    'CAMS': 'CAMS',
    'CONCORDBIO': 'CONCORDBIO',
    'CONCOR': 'CONCOR',
    'COROMANDEL': 'COROMANDEL',
    'CRAFTSMAN': 'CRAFTSMAN',
    'CREDITACC': 'CREDITACC',
    'CROMPTON': 'CROMPTON',
    'CUMMINSIND': 'CUMMINSIND',
    'CYIENT': 'CYIENT',
    'DCMSHRIRAM': 'DCMSHRIRAM',
    'DLF': 'DLF',
    'DOMS': 'DOMS',
    'DABUR': 'DABUR',
    'DALBHARAT': 'DALBHARAT',
    'DATAPATTNS': 'DATAPATTNS',
    'DEEPAKFERT': 'DEEPAKFERT',
    'DEEPAKNTR': 'DEEPAKNTR',
    'DELHIVERY': 'DELHIVERY',
    'DEVYANI': 'DEVYANI',
    'DIVISLAB': 'DIVISLAB',
    'DIXON': 'DIXON',
    'LALPATHLAB': 'LALPATHLAB',
    'DRREDDY': 'DRREDDY',
    'DUMMYSIEMS': 'DUMMYSIEMS',
    'EIDPARRY': 'EIDPARRY',
    'EIHOTEL': 'EIHOTEL',
    'EICHERMOT': 'EICHERMOT',
    'ELECON': 'ELECON',
    'ELGIEQUIP': 'ELGIEQUIP',
    'EMAMILTD': 'EMAMILTD',
    'EMCURE': 'EMCURE',
    'ENDURANCE': 'ENDURANCE',
    'ENGINERSIN': 'ENGINERSIN',
    'ERIS': 'ERIS',
    'ESCORTS': 'ESCORTS',
    'ETERNAL': 'ETERNAL',
    'EXIDEIND': 'EXIDEIND',
    'NYKAA': 'NYKAA',
    'FEDERALBNK': 'FEDERALBNK',
    'FACT': 'FACT',
    'FINCABLES': 'FINCABLES',
    'FINPIPE': 'FINPIPE',
    'FSL': 'FSL',
    'FIVESTAR': 'FIVESTAR',
    'FORTIS': 'FORTIS',
    'GAIL': 'GAIL',
    'GVT&D': 'GVT&D',
    'GMRAIRPORT': 'GMRAIRPORT',
    'GRSE': 'GRSE',
    'GICRE': 'GICRE',
    'GILLETTE': 'GILLETTE',
    'GLAND': 'GLAND',
    'GLAXO': 'GLAXO',
    'GLENMARK': 'GLENMARK',
    'MEDANTA': 'MEDANTA',
    'GODIGIT': 'GODIGIT',
    'GPIL': 'GPIL',
    'GODFRYPHLP': 'GODFRYPHLP',
    'GODREJAGRO': 'GODREJAGRO',
    'GODREJCP': 'GODREJCP',
    'GODREJIND': 'GODREJIND',
    'GODREJPROP': 'GODREJPROP',
    'GRANULES': 'GRANULES',
    'GRAPHITE': 'GRAPHITE',
    'GRASIM': 'GRASIM',
    'GRAVITA': 'GRAVITA',
    'GESHIP': 'GESHIP',
    'FLUOROCHEM': 'FLUOROCHEM',
    'GUJGASLTD': 'GUJGASLTD',
    'GMDCLTD': 'GMDCLTD',
    'GNFC': 'GNFC',
    'GPPL': 'GPPL',
    'GSPL': 'GSPL',
    'HEG': 'HEG',
    'HBLENGINE': 'HBLENGINE',
    'HCLTECH': 'HCLTECH',
    'HDFCAMC': 'HDFCAMC',
    'HDFCBANK': 'HDFCBANK',
    'HDFCLIFE': 'HDFCLIFE',
    'HFCL': 'HFCL',
    'HAPPSTMNDS': 'HAPPSTMNDS',
    'HAVELLS': 'HAVELLS',
    'HEROMOTOCO': 'HEROMOTOCO',
    'HSCL': 'HSCL',
    'HINDALCO': 'HINDALCO',
    'HAL': 'HAL',
    'HINDCOPPER': 'HINDCOPPER',
    'HINDPETRO': 'HINDPETRO',
    'HINDUNILVR': 'HINDUNILVR',
    'HINDZINC': 'HINDZINC',
    'POWERINDIA': 'POWERINDIA',
    'HOMEFIRST': 'HOMEFIRST',
    'HONASA': 'HONASA',
    'HONAUT': 'HONAUT',
    'HUDCO': 'HUDCO',
    'HYUNDAI': 'HYUNDAI',
    'ICICIBANK': 'ICICIBANK',
    'ICICIGI': 'ICICIGI',
    'ICICIPRULI': 'ICICIPRULI',
    'IDBI': 'IDBI',
    'IDFCFIRSTB': 'IDFCFIRSTB',
    'IFCI': 'IFCI',
    'IIFL': 'IIFL',
    'INOXINDIA': 'INOXINDIA',
    'IRB': 'IRB',
    'IRCON': 'IRCON',
    'ITC': 'ITC',
    'ITI': 'ITI',
    'INDGN': 'INDGN',
    'INDIACEM': 'INDIACEM',
    'INDIAMART': 'INDIAMART',
    'INDIANB': 'INDIANB',
    'IEX': 'IEX',
    'INDHOTEL': 'INDHOTEL',
    'IOC': 'IOC',
    'IOB': 'IOB',
    'IRCTC': 'IRCTC',
    'IRFC': 'IRFC',
    'IREDA': 'IREDA',
    'IGL': 'IGL',
    'INDUSTOWER': 'INDUSTOWER',
    'INDUSINDBK': 'INDUSINDBK',
    'NAUKRI': 'NAUKRI',
    'INFY': 'INFY',
    'INOXWIND': 'INOXWIND',
    'INTELLECT': 'INTELLECT',
    'INDIGO': 'INDIGO',
    'IGIL': 'IGIL',
    'IKS': 'IKS',
    'IPCALAB': 'IPCALAB',
    'JBCHEPHARM': 'JBCHEPHARM',
    'JKCEMENT': 'JKCEMENT',
    'JBMA': 'JBMA',
    'JKTYRE': 'JKTYRE',
    'JMFINANCIL': 'JMFINANCIL',
    'JSWENERGY': 'JSWENERGY',
    'JSWHL': 'JSWHL',
    'JSWINFRA': 'JSWINFRA',
    'JSWSTEEL': 'JSWSTEEL',
    'JPPOWER': 'JPPOWER',
    'J&KBANK': 'J&KBANK',
    'JINDALSAW': 'JINDALSAW',
    'JSL': 'JSL',
    'JINDALSTEL': 'JINDALSTEL',
    'JIOFIN': 'JIOFIN',
    'JUBLFOOD': 'JUBLFOOD',
    'JUBLINGREA': 'JUBLINGREA',
    'JUBLPHARMA': 'JUBLPHARMA',
    'JWL': 'JWL',
    'JUSTDIAL': 'JUSTDIAL',
    'JYOTHYLAB': 'JYOTHYLAB',
    'JYOTICNC': 'JYOTICNC',
    'KPRMILL': 'KPRMILL',
    'KEI': 'KEI',
    'KNRCON': 'KNRCON',
    'KPITTECH': 'KPITTECH',
    'KAJARIACER': 'KAJARIACER',
    'KPIL': 'KPIL',
    'KALYANKJIL': 'KALYANKJIL',
    'KANSAINER': 'KANSAINER',
    'KARURVYSYA': 'KARURVYSYA',
    'KAYNES': 'KAYNES',
    'KEC': 'KEC',
    'KFINTECH': 'KFINTECH',
    'KIRLOSBROS': 'KIRLOSBROS',
    'KIRLOSENG': 'KIRLOSENG',
    'KOTAKBANK': 'KOTAKBANK',
    'KIMS': 'KIMS',
    'LTF': 'LTF',
    'LTTS': 'LTTS',
    'LICHSGFIN': 'LICHSGFIN',
    'LTFOODS': 'LTFOODS',
    'LTIM': 'LTIM',
    'LT': 'LT',
    'LATENTVIEW': 'LATENTVIEW',
    'LAURUSLABS': 'LAURUSLABS',
    'LEMONTREE': 'LEMONTREE',
    'LICI': 'LICI',
    'LINDEINDIA': 'LINDEINDIA',
    'LLOYDSME': 'LLOYDSME',
    'LUPIN': 'LUPIN',
    'MMTC': 'MMTC',
    'MRF': 'MRF',
    'LODHA': 'LODHA',
    'MGL': 'MGL',
    'MAHSEAMLES': 'MAHSEAMLES',
    'M&MFIN': 'M&MFIN',
    'M&M': 'M&M',
    'MANAPPURAM': 'MANAPPURAM',
    'MRPL': 'MRPL',
    'MANKIND': 'MANKIND',
    'MARICO': 'MARICO',
    'MARUTI': 'MARUTI',
    'MASTEK': 'MASTEK',
    'MFSL': 'MFSL',
    'MAXHEALTH': 'MAXHEALTH',
    'MAZDOCK': 'MAZDOCK',
    'METROPOLIS': 'METROPOLIS',
    'MINDACORP': 'MINDACORP',
    'MSUMI': 'MSUMI',
    'MOTILALOFS': 'MOTILALOFS',
    'MPHASIS': 'MPHASIS',
    'MCX': 'MCX',
    'MUTHOOTFIN': 'MUTHOOTFIN',
    'NATCOPHARM': 'NATCOPHARM',
    'NBCC': 'NBCC',
    'NCC': 'NCC',
    'NHPC': 'NHPC',
    'NLCINDIA': 'NLCINDIA',
    'NMDC': 'NMDC',
    'NSLNISP': 'NSLNISP',
    'NTPCGREEN': 'NTPCGREEN',
    'NTPC': 'NTPC',
    'NH': 'NH',
    'NATIONALUM': 'NATIONALUM',
    'NAVA': 'NAVA',
    'NAVINFLUOR': 'NAVINFLUOR',
    'NESTLEIND': 'NESTLEIND',
    'NETWEB': 'NETWEB',
    'NETWORK18': 'NETWORK18',
    'NEULANDLAB': 'NEULANDLAB',
    'NEWGEN': 'NEWGEN',
    'NAM-INDIA': 'NAM-INDIA',
    'NIVABUPA': 'NIVABUPA',
    'NUVAMA': 'NUVAMA',
    'OBEROIRLTY': 'OBEROIRLTY',
    'ONGC': 'ONGC',
    'OIL': 'OIL',
    'OLAELEC': 'OLAELEC',
    'OLECTRA': 'OLECTRA',
    'PAYTM': 'PAYTM',
    'OFSS': 'OFSS',
    'POLICYBZR': 'POLICYBZR',
    'PCBL': 'PCBL',
    'PGEL': 'PGEL',
    'PIIND': 'PIIND',
    'PNBHOUSING': 'PNBHOUSING',
    'PNCINFRA': 'PNCINFRA',
    'PTCIL': 'PTCIL',
    'PVRINOX': 'PVRINOX',
    'PAGEIND': 'PAGEIND',
    'PATANJALI': 'PATANJALI',
    'PERSISTENT': 'PERSISTENT',
    'PETRONET': 'PETRONET',
    'PFIZER': 'PFIZER',
    'PHOENIXLTD': 'PHOENIXLTD',
    'PIDILITIND': 'PIDILITIND',
    'PEL': 'PEL',
    'PPLPHARMA': 'PPLPHARMA',
    'POLYMED': 'POLYMED',
    'POLYCAB': 'POLYCAB',
    'POONAWALLA': 'POONAWALLA',
    'PFC': 'PFC',
    'POWERGRID': 'POWERGRID',
    'PRAJIND': 'PRAJIND',
    'PREMIERENE': 'PREMIERENE',
    'PRESTIGE': 'PRESTIGE',
    'PNB': 'PNB',
    'RRKABEL': 'RRKABEL',
    'RBLBANK': 'RBLBANK',
    'RECLTD': 'RECLTD',
    'RHIM': 'RHIM',
    'RITES': 'RITES',
    'RADICO': 'RADICO',
    'RVNL': 'RVNL',
    'RAILTEL': 'RAILTEL',
    'RAINBOW': 'RAINBOW',
    'RKFORGE': 'RKFORGE',
    'RCF': 'RCF',
    'RTNINDIA': 'RTNINDIA',
    'RAYMONDLSL': 'RAYMONDLSL',
    'RAYMOND': 'RAYMOND',
    'REDINGTON': 'REDINGTON',
    'RELIANCE': 'RELIANCE',
    'RPOWER': 'RPOWER',
    'ROUTE': 'ROUTE',
    'SBFC': 'SBFC',
    'SBICARD': 'SBICARD',
    'SBILIFE': 'SBILIFE',
    'SJVN': 'SJVN',
    'SKFINDIA': 'SKFINDIA',
    'SRF': 'SRF',
    'SAGILITY': 'SAGILITY',
    'SAILIFE': 'SAILIFE',
    'SAMMAANCAP': 'SAMMAANCAP',
    'MOTHERSON': 'MOTHERSON',
    'SAPPHIRE': 'SAPPHIRE',
    'SARDAEN': 'SARDAEN',
    'SAREGAMA': 'SAREGAMA',
    'SCHAEFFLER': 'SCHAEFFLER',
    'SCHNEIDER': 'SCHNEIDER',
    'SCI': 'SCI',
    'SHREECEM': 'SHREECEM',
    'RENUKA': 'RENUKA',
    'SHRIRAMFIN': 'SHRIRAMFIN',
    'SHYAMMETL': 'SHYAMMETL',
    'SIEMENS': 'SIEMENS',
    'SIGNATURE': 'SIGNATURE',
    'SOBHA': 'SOBHA',
    'SOLARINDS': 'SOLARINDS',
    'SONACOMS': 'SONACOMS',
    'SONATSOFTW': 'SONATSOFTW',
    'STARHEALTH': 'STARHEALTH',
    'SBIN': 'SBIN',
    'SAIL': 'SAIL',
    'SWSOLAR': 'SWSOLAR',
    'SUMICHEM': 'SUMICHEM',
    'SUNPHARMA': 'SUNPHARMA',
    'SUNTV': 'SUNTV',
    'SUNDARMFIN': 'SUNDARMFIN',
    'SUNDRMFAST': 'SUNDRMFAST',
    'SUPREMEIND': 'SUPREMEIND',
    'SUVENPHAR': 'SUVENPHAR',
    'SUZLON': 'SUZLON',
    'SWANENERGY': 'SWANENERGY',
    'SWIGGY': 'SWIGGY',
    'SYNGENE': 'SYNGENE',
    'SYRMA': 'SYRMA',
    'TBOTEK': 'TBOTEK',
    'TVSMOTOR': 'TVSMOTOR',
    'TANLA': 'TANLA',
    'TATACHEM': 'TATACHEM',
    'TATACOMM': 'TATACOMM',
    'TCS': 'TCS',
    'TATACONSUM': 'TATACONSUM',
    'TATAELXSI': 'TATAELXSI',
    'TATAINVEST': 'TATAINVEST',
    'TATAMOTORS': 'TATAMOTORS',
    'TATAPOWER': 'TATAPOWER',
    'TATASTEEL': 'TATASTEEL',
    'TATATECH': 'TATATECH',
    'TTML': 'TTML',
    'TECHM': 'TECHM',
    'TECHNOE': 'TECHNOE',
    'TEJASNET': 'TEJASNET',
    'NIACL': 'NIACL',
    'RAMCOCEM': 'RAMCOCEM',
    'THERMAX': 'THERMAX',
    'TIMKEN': 'TIMKEN',
    'TITAGARH': 'TITAGARH',
    'TITAN': 'TITAN',
    'TORNTPHARM': 'TORNTPHARM',
    'TORNTPOWER': 'TORNTPOWER',
    'TARIL': 'TARIL',
    'TRENT': 'TRENT',
    'TRIDENT': 'TRIDENT',
    'TRIVENI': 'TRIVENI',
    'TRITURBINE': 'TRITURBINE',
    'TIINDIA': 'TIINDIA',
    'UCOBANK': 'UCOBANK',
    'UNOMINDA': 'UNOMINDA',
    'UPL': 'UPL',
    'UTIAMC': 'UTIAMC',
    'ULTRACEMCO': 'ULTRACEMCO',
    'UNIONBANK': 'UNIONBANK',
    'UBL': 'UBL',
    'UNITDSPR': 'UNITDSPR',
    'USHAMART': 'USHAMART',
    'VGUARD': 'VGUARD',
    'DBREALTY': 'DBREALTY',
    'VTL': 'VTL',
    'VBL': 'VBL',
    'MANYAVAR': 'MANYAVAR',
    'VEDL': 'VEDL',
    'VIJAYA': 'VIJAYA',
    'VMM': 'VMM',
    'IDEA': 'IDEA',
    'VOLTAS': 'VOLTAS',
    'WAAREEENER': 'WAAREEENER',
    'WELCORP': 'WELCORP',
    'WELSPUNLIV': 'WELSPUNLIV',
    'WESTLIFE': 'WESTLIFE',
    'WHIRLPOOL': 'WHIRLPOOL',
    'WIPRO': 'WIPRO',
    'WOCKPHARMA': 'WOCKPHARMA',
    'YESBANK': 'YESBANK',
    'ZFCVINDIA': 'ZFCVINDIA',
    'ZEEL': 'ZEEL',
    'ZENTEC': 'ZENTEC',
    'ZENSARTECH': 'ZENSARTECH',
    'ZYDUSLIFE': 'ZYDUSLIFE',
    'ECLERX': 'ECLERX'
}

# Common words to exclude from company name detection
COMMON_WORDS = {
    'LTD', 'LIMITED', 'AND', 'THE', 'OF', 'IN', 'FOR', 'TO', 'WITH', 'BY',
    'FROM', 'ON', 'AT', 'AS', 'IS', 'ARE', 'WAS', 'WERE', 'BE', 'BEEN',
    'BEING', 'HAVE', 'HAS', 'HAD', 'DO', 'DOES', 'DID', 'WILL', 'WOULD',
    'SHALL', 'SHOULD', 'MAY', 'MIGHT', 'MUST', 'CAN', 'COULD', 'A', 'AN',
    'THIS', 'THAT', 'THESE', 'THOSE', 'IT', 'ITS', 'THEY', 'THEM', 'THEIR',
    'WE', 'US', 'OUR', 'YOU', 'YOUR', 'HE', 'HIM', 'HIS', 'SHE', 'HER',
    'HERS', 'I', 'ME', 'MY', 'MINE'
}

def get_company_symbol(company_name: str) -> str:
    """Get the NSE symbol for a company name."""
    # Clean and normalize the company name
    clean_name = company_name.upper().strip()
    # Remove common suffixes
    clean_name = re.sub(r'\s+(LTD|LIMITED|INC|INCORPORATED|CORP|CORPORATION)$', '', clean_name)
    
    # Try to find a match in NSE500_COMPANIES
    for company in NSE500_COMPANIES:
        company_parts = company.split()
        if len(company_parts) > 0:
            # Check if the company name matches any part of the entry
            if clean_name in company or company in clean_name:
                return company_parts[0]  # Return the symbol (first word)
    
    return "Unknown"

def is_valid_company_name(text: str) -> bool:
    """Check if the text contains a valid NSE500 company name."""
    words = text.upper().split()
    # Remove common words and short words
    words = [w for w in words if w not in COMMON_WORDS and len(w) > 2]
    
    # Check if any word or combination of words matches a company name
    for i in range(len(words)):
        for j in range(i + 1, min(i + 4, len(words) + 1)):
            potential_name = ' '.join(words[i:j])
            for company in NSE500_COMPANIES:
                if potential_name in company or company in potential_name:
                    return True
    
    return False

def extract_company_name(text: str) -> Tuple[str, str]:
    """Extract company name and symbol from text."""
    words = text.upper().split()
    # Remove common words and short words
    words = [w for w in words if w not in COMMON_WORDS and len(w) > 2]
    
    # Try to find the longest matching company name
    best_match = None
    best_length = 0
    
    for i in range(len(words)):
        for j in range(i + 1, min(i + 4, len(words) + 1)):
            potential_name = ' '.join(words[i:j])
            for company in NSE500_COMPANIES:
                if potential_name in company or company in potential_name:
                    if len(company) > best_length:
                        best_match = company
                        best_length = len(company)
    
    if best_match:
        return best_match, best_match.split()[0]  # Return full name and symbol
    
    return "Unknown", "Unknown" 