import os
from datetime import datetime, timezone, timedelta
from collections import defaultdict

# ===== Date Configuration =====
START_DATE = datetime(2025, 5, 12, tzinfo=timezone.utc)
END_DATE = datetime(2025, 5, 14, tzinfo=timezone.utc)

# ===== Telegram Configuration =====
TELEGRAM_API_ID = "API_ID"
TELEGRAM_API_HASH = "API_HASH"
TELEGRAM_BOT_TOKEN = f"{TELEGRAM_API_ID}:{TELEGRAM_API_HASH}"
TELEGRAM_CHANNELS = [
    "nse_updates_live",
    "Companyupdate",
    "researchreportss",
    "btsreports",
    "aoiventuresltd",
    "ipoinfo3",
    "ExencialResearch"
]

# ===== Data Categories =====
DATA_CATEGORIES = [
    "Company Performance",
    "Management Updates",
    "Market Sentiment",
    "Financial Results",
    "Industry News",
    "Regulatory Updates",
    "Technical Analysis",
    "Investment Recommendations"
]

# ===== Sentiment Categories =====
SENTIMENT_CATEGORIES = ["Positive", "Negative", "Neutral"]

# ===== API Rate Limits =====
API_RATE_LIMITS = {
    "telegram": {
        "requests_per_minute": 30,
        "requests_per_hour": 1000
    }
}

# ===== File Paths =====
DATA_DIR = "data"
RAW_DATA_DIR = f"{DATA_DIR}/raw"
PROCESSED_DATA_DIR = f"{DATA_DIR}/processed"
VISUALIZATIONS_DIR = f"{DATA_DIR}/visualizations"
REPORTS_DIR = f"{DATA_DIR}/reports"

# ===== NSE 500 Companies Mapping =====
NSE500_COMPANIES = [
    "360ONE", "360 ONE WAM Ltd.", "360 ONE", "360 ONE WAM",
    "3MINDIA", "3M India Ltd.", "3M India",
     "ABB India Ltd.", "ABB India", 
    "ACMESOLAR", "ACME Solar Holdings Ltd.", "ACME Solar", "ACME",
    "AIAENG", "AIA Engineering Ltd.", "AIA Engineering", "AIA",
    "APLAPOLLO", "APL Apollo Tubes Ltd.", "APL Apollo", "Apollo Tubes",
    "AUBANK", "AU Small Finance Bank Ltd.", "AU Small Finance", "AU Bank",
    "AWL", "AWL Agri Business Ltd.", "AWL Agri", "AWL",
    "AADHARHFC", "Aadhar Housing Finance Ltd.", "Aadhar Housing", "Aadhar",
    "AARTIIND", "Aarti Industries Ltd.", "Aarti Industries", "Aarti",
    "AAVAS", "Aavas Financiers Ltd.", "Aavas Financiers", "Aavas",
    "ABBOTINDIA", "Abbott India Ltd.", "Abbott India", "Abbott",
     "Action Construction Equipment Ltd.", "Action Construction", 
    "ADANIENSOL", "Adani Energy Solutions Ltd.", "Adani Energy", 
    "ADANIENT", "Adani Enterprises Ltd.", "Adani Enterprises", 
    "ADANIGREEN", "Adani Green Energy Ltd.", "Adani Green", 
    "ADANIPORTS", "Adani Ports and Special Economic Zone Ltd.", "Adani Ports", 
    "ADANIPOWER", "Adani Power Ltd.", "Adani Power", 
    "ATGL", "Adani Total Gas Ltd.", "Adani Total Gas",
    "ABCAPITAL", "Aditya Birla Capital Ltd.", "Aditya Birla Capital", 
    "ABFRL", "Aditya Birla Fashion and Retail Ltd.", "Aditya Birla Fashion", 
    "ABREL", "Aditya Birla Real Estate Ltd.", "Aditya Birla Real Estate", 
    "ABSLAMC", "Aditya Birla Sun Life AMC Ltd.", "Aditya Birla Sun Life", 
    "AEGISLOG", "Aegis Logistics Ltd.", "Aegis Logistics", "Aegis",
    "AFCONS", "Afcons Infrastructure Ltd.", "Afcons Infrastructure", "Afcons",
    "AFFLE", "Affle 3i Ltd.", "Affle 3i", "Affle",
    "AJANTPHARM", "Ajanta Pharmaceuticals Ltd.", "Ajanta Pharma", "Ajanta",
    "AKUMS", "Akums Drugs and Pharmaceuticals Ltd.", "Akums Drugs", "Akums",
    "APLLTD", "Alembic Pharmaceuticals Ltd.", "Alembic Pharma", "Alembic",
    "ALIVUS", "Alivus Life Sciences Ltd.", "Alivus Life Sciences", "Alivus",
    "ALKEM", "Alkem Laboratories Ltd.", "Alkem Labs", "Alkem",
    "ALKYLAMINE", "Alkyl Amines Chemicals Ltd.", "Alkyl Amines", 
    "ALOKINDS", "Alok Industries Ltd.", "Alok Industries", 
    "ARE&M", "Amara Raja Energy & Mobility Ltd.", "Amara Raja", "Amara",
     "Amber Enterprises India Ltd.", "Amber Enterprises", 
    "AMBUJACEM", "Ambuja Cements Ltd.", "Ambuja Cements", "Ambuja",
    "ANANDRATHI", "Anand Rathi Wealth Ltd.", "Anand Rathi",
    "ANANTRAJ", "Anant Raj Ltd.", "Anant Raj",
    "ANGELONE", "Angel One Ltd.", "Angel One", 
    "APARINDS", "Apar Industries Ltd.", "Apar Industries", 
    "APOLLOHOSP", "Apollo Hospitals Enterprise Ltd.", "Apollo Hospitals", 
    "APOLLOTYRE", "Apollo Tyres Ltd.", "Apollo Tyres",
    "APTUS", "Aptus Value Housing Finance India Ltd.", "Aptus Value Housing", "Aptus",
    "ASAHIINDIA", "Asahi India Glass Ltd.", "Asahi India", "Asahi",
    "ASHOKLEY", "Ashok Leyland Ltd.", "Ashok Leyland", 
    "ASIANPAINT", "Asian Paints Ltd.", "Asian Paints",
    "ASTERDM", "Aster DM Healthcare Ltd.", "Aster DM", "Aster",
    "ASTRAZEN", "AstraZenca Pharma India Ltd.", "AstraZenca Pharma", "AstraZenca",
    "ASTRAL", "Astral Ltd.", "Astral",
     "Atul Ltd."
    "AUROPHARMA", "Aurobindo Pharma Ltd.", "Aurobindo Pharma", "Aurobindo",
    "AIIL", "Authum Investment & Infrastructure Ltd.", "Authum Investment", "Authum",
    "DMART", "Avenue Supermarts Ltd.", "Avenue Supermarts", "DMart",
    "AXISBANK", "Axis Bank Ltd.", "Axis Bank",
    "BASF", "BASF India Ltd.", "BASF India", "BASF",
    "BEML", "BEML Ltd.", "BEML",
    "BLS", "BLS International Services Ltd.", "BLS International", "BLS",
    "BSE", "BSE Ltd.", "BSE",
    "BAJAJ-AUTO", "Bajaj Auto Ltd.", "Bajaj Auto", 
    "BAJFINANCE", "Bajaj Finance Ltd.", "Bajaj Finance", 
    "BAJAJFINSV", "Bajaj Finserv Ltd.", "Bajaj Finserv", 
    "BAJAJHLDNG", "Bajaj Holdings & Investment Ltd.", "Bajaj Holdings", 
    "BAJAJHFL", "Bajaj Housing Finance Ltd.", "Bajaj Housing",
    "BALKRISIND", "Balkrishna Industries Ltd.", "Balkrishna Industries", "Balkrishna",
    "BALRAMCHIN", "Balrampur Chini Mills Ltd.", "Balrampur Chini", "Balrampur",
    "BANDHANBNK", "Bandhan Bank Ltd.", "Bandhan Bank", "Bandhan",
    "BANKBARODA", "Bank of Baroda", "Bank of Baroda", "BOB",
    "BANKINDIA", "Bank of India", "Bank of India", "BOI",
    "MAHABANK", "Bank of Maharashtra", "Bank of Maharashtra", "Mahabank",
    "BATAINDIA", "Bata India Ltd.", "Bata India", "Bata",
    "BAYERCROP", "Bayer Cropscience Ltd.", "Bayer Cropscience", "Bayer",
    "BERGEPAINT", "Berger Paints India Ltd.", "Berger Paints", "Berger",
    "BDL", "Bharat Dynamics Ltd.", "Bharat Dynamics", 
     "Bharat Electronics Ltd.", "Bharat Electronics", 
    "BHARATFORG", "Bharat Forge Ltd.", "Bharat Forge", 
    "BHEL", "Bharat Heavy Electricals Ltd.", "Bharat Heavy Electricals", 
    "BPCL", "Bharat Petroleum Corporation Ltd.", "Bharat Petroleum", "BPCL",
    "BHARTIARTL", "Bharti Airtel Ltd.", "Bharti Airtel", 
    "BHARTIHEXA", "Bharti Hexacom Ltd.", "Bharti Hexacom", "Hexacom",
    "BIKAJI", "Bikaji Foods International Ltd.", "Bikaji Foods", "Bikaji",
    "BIOCON", "Biocon Ltd.", "Biocon",
    "BSOFT", "Birlasoft Ltd.", "Birlasoft", "BSOFT",
    "BLUEDART", "Blue Dart Express Ltd.", "Blue Dart", 
    "BLUESTARCO", "Blue Star Ltd.", "Blue Star",
    "BBTC", "Bombay Burmah Trading Corporation Ltd.", "Bombay Burmah", "BBTC",
    "BOSCHLTD", "Bosch Ltd.", "Bosch",
    "FIRSTCRY", "Brainbees Solutions Ltd.", "Brainbees", "FirstCry",
    "BRIGADE", "Brigade Enterprises Ltd.", "Brigade Enterprises", "Brigade",
    "BRITANNIA", "Britannia Industries Ltd.", "Britannia Industries", "Britannia",
    "MAPMYINDIA", "C.E. Info Systems Ltd.", "C.E. Info Systems", "MapmyIndia",
    "CCL", "CCL Products (I) Ltd.", "CCL Products", "CCL",
    "CESC", "CESC Ltd.", "CESC",
    "CGPOWER", "CG Power and Industrial Solutions Ltd.", "CG Power", "CG",
    "CRISIL", "CRISIL Ltd.", "CRISIL",
    "CAMPUS", "Campus Activewear Ltd.", "Campus Activewear", "Campus",
    "CANFINHOME", "Can Fin Homes Ltd.", "Can Fin Homes", "Can Fin",
    "CANBK", "Canara Bank", "Canara Bank", "Canara",
    "CAPLIPOINT", "Caplin Point Laboratories Ltd.", "Caplin Point", "Caplin",
    "CGCL", "Capri Global Capital Ltd.", "Capri Global", "Capri",
    "CARBORUNIV", "Carborundum Universal Ltd.", "Carborundum Universal", "Carborundum",
    "CASTROLIND", "Castrol India Ltd.", "Castrol India", "Castrol",
    "CEATLTD", "Ceat Ltd.", "Ceat",
    "CENTRALBK", "Central Bank of India", "Central Bank", "CBI",
    "CDSL", "Central Depository Services (India) Ltd.", "Central Depository Services", "CDSL",
    "CENTURYPLY", "Century Plyboards (India) Ltd.", "Century Plyboards", "Century",
    "CERA", "Cera Sanitaryware Ltd.", "Cera Sanitaryware", "Cera",
    "CHALET", "Chalet Hotels Ltd.", "Chalet Hotels", "Chalet",
    "CHAMBLFERT", "Chambal Fertilizers & Chemicals Ltd.", "Chambal Fertilizers", "Chambal",
    "CHENNPETRO", "Chennai Petroleum Corporation Ltd.", "Chennai Petroleum", "CPCL",
    "CHOLAHLDNG", "Cholamandalam Financial Holdings Ltd.", "Cholamandalam Financial", "Cholamandalam",
    "CHOLAFIN", "Cholamandalam Investment and Finance Company Ltd.", "Cholamandalam Investment", "Cholamandalam",
    "CIPLA", "Cipla Ltd.", "Cipla",
    "CUB", "City Union Bank Ltd.", "City Union Bank", "CUB",
     "Clean Science and Technology Ltd.", "Clean Science", 
    "COALINDIA", "Coal India Ltd.", "Coal India",
    "COCHINSHIP", "Cochin Shipyard Ltd.", "Cochin Shipyard", "Cochin",
    "COFORGE", "Coforge Ltd.", "Coforge",
    "COLPAL", "Colgate Palmolive (India) Ltd.", "Colgate Palmolive", "Colgate",
    "CAMS", "Computer Age Management Services Ltd.", "Computer Age Management", "CAMS",
    "CONCORDBIO", "Concord Biotech Ltd.", "Concord Biotech", "Concord",
    "CONCOR", "Container Corporation of India Ltd.", "Container Corporation", "Concor",
    "COROMANDEL", "Coromandel International Ltd.", "Coromandel International", "Coromandel",
    "CRAFTSMAN", "Craftsman Automation Ltd.", "Craftsman Automation", "Craftsman",
    "CREDITACC", "CreditAccess Grameen Ltd.", "CreditAccess Grameen", "CreditAccess",
    "CROMPTON", "Crompton Greaves Consumer Electricals Ltd.", "Crompton Greaves", "Crompton",
    "CUMMINSIND", "Cummins India Ltd.", "Cummins India", "Cummins",
    "CYIENT", "Cyient Ltd.", "Cyient",
    "DCMSHRIRAM", "DCM Shriram Ltd.", "DCM Shriram", "DCM",
    "DLF", "DLF Ltd.", 
    "DOMS", "DOMS Industries Ltd.", "DOMS Industries", "DOMS",
    "DABUR", "Dabur India Ltd.", "Dabur India", "Dabur",
    "DALBHARAT", "Dalmia Bharat Ltd.", "Dalmia Bharat", "Dalmia",
    "DATAPATTNS", "Data Patterns (India) Ltd.", "Data Patterns", 
    "DEEPAKFERT", "Deepak Fertilisers & Petrochemicals Corp. Ltd.", "Deepak Fertilisers", "Deepak",
    "DEEPAKNTR", "Deepak Nitrite Ltd.", "Deepak Nitrite", 
    "DELHIVERY", "Delhivery Ltd.", "Delhivery",
    "DEVYANI", "Devyani International Ltd.", "Devyani International", 
    "DIVISLAB", "Divi's Laboratories Ltd.", "Divi's Laboratories", 
    "DIXON", "Dixon Technologies (India) Ltd.", "Dixon Technologies", "Dixon",
    "LALPATHLAB", "Dr. Lal Path Labs Ltd.", "Dr. Lal Path Labs", "Lal Path",
    "DRREDDY", "Dr. Reddy's Laboratories Ltd.", "Dr. Reddy's", "Dr. Reddy",
    "DUMMYSIEMS", "Dummy Siemens Ltd.", "Dummy Siemens", "Siemens",
    "EIDPARRY", "E.I.D. Parry (India) Ltd.", "E.I.D. Parry", 
    "EIHOTEL", "EIH Ltd.",  "EIH Hotel",
    "EICHERMOT", "Eicher Motors Ltd.", "Eicher Motors", "Eicher",
    "ELECON", "Elecon Engineering Co. Ltd.", "Elecon Engineering", "Elecon",
    "ELGIEQUIP", "Elgi Equipments Ltd.", "Elgi Equipments",
    "EMAMILTD", "Emami Ltd.", "Emami",
    "EMCURE", "Emcure Pharmaceuticals Ltd.", "Emcure Pharma", "Emcure",
    "ENDURANCE", "Endurance Technologies Ltd.", "Endurance Technologies", "Endurance",
    "ENGINERSIN", "Engineers India Ltd.", "Engineers India", 
    "ERIS", "Eris Lifesciences Ltd.", "Eris Lifesciences", 
    "ESCORTS", "Escorts Kubota Ltd.", "Escorts Kubota", "Escorts",
    "ETERNAL", "Eternal Ltd.", "Eternal",
    "EXIDEIND", "Exide Industries Ltd.", "Exide Industries", "Exide",
    "NYKAA", "FSN E-Commerce Ventures Ltd.", "FSN E-Commerce", "Nykaa",
    "FEDERALBNK", "Federal Bank Ltd.", "Federal Bank", "Federal",
  "FACT", "Fertilisers and Chemicals Travancore Ltd.", "Fertilisers Travancore", 
    "FINCABLES", "Finolex Cables Ltd.", "Finolex Cables", "Finolex",
    "FINPIPE", "Finolex Industries Ltd.", "Finolex Industries", "Finolex",
    "FSL", "Firstsource Solutions Ltd.", "Firstsource Solutions", "Firstsource",
    "FIVESTAR", "Five-Star Business Finance Ltd.", "Five-Star Business", "Five-Star",
    "FORTIS", "Fortis Healthcare Ltd.", "Fortis Healthcare", "Fortis",
    "GAIL", "GAIL (India) Ltd.", "GAIL India", "GAIL",
    "GVT&D", "GE Vernova T&D India Ltd.", "GE Vernova", "Vernova",
    "GMRAIRPORT", "GMR Airports Ltd.", "GMR Airports", "GMR",
    "GRSE", "Garden Reach Shipbuilders & Engineers Ltd.", "Garden Reach", "GRSE",
    "GICRE", "General Insurance Corporation of India", "General Insurance", 
    "GILLETTE", "Gillette India Ltd.", "Gillette India", "Gillette",
    "GLAND", "Gland Pharma Ltd.", "Gland Pharma", "Gland",
    "GLAXO", "Glaxosmithkline Pharmaceuticals Ltd.", "Glaxosmithkline", "Glaxo",
    "MEDANTA", "Global Health Ltd.", "Global Health", "Medanta",
    "GODIGIT", "Go Digit General Insurance Ltd.", "Go Digit", 
    "GPIL", "Godawari Power & Ispat Ltd.", "Godawari Power", "Godawari",
    "GODFRYPHLP", "Godfrey Phillips India Ltd.", "Godfrey Phillips", "Godfrey",
    "GODREJAGRO", "Godrej Agrovet Ltd.", "Godrej Agrovet", "Godrej",
    "GODREJCP", "Godrej Consumer Products Ltd.", "Godrej Consumer", "Godrej",
    "GODREJIND", "Godrej Industries Ltd.", "Godrej Industries", "Godrej",
    "GODREJPROP", "Godrej Properties Ltd.", "Godrej Properties", "Godrej",
    "GRANULES", "Granules India Ltd.", "Granules India", "Granules",
    "GRAPHITE", "Graphite India Ltd.", "Graphite India", "Graphite",
    "GRASIM", "Grasim Industries Ltd.", "Grasim Industries", "Grasim",
    "GRAVITA", "Gravita India Ltd.", "Gravita India", "Gravita",
    "GESHIP", "Great Eastern Shipping Co. Ltd.", "Great Eastern Shipping", "GESHIP",
    "FLUOROCHEM", "Gujarat Fluorochemicals Ltd.", "Gujarat Fluorochemicals", "Fluorochem",
    "GUJGASLTD", "Gujarat Gas Ltd.", "Gujarat Gas", "Guj Gas",
    "GMDCLTD", "Gujarat Mineral Development Corporation Ltd.", "Gujarat Mineral", "GMDC",
    "GNFC", "Gujarat Narmada Valley Fertilizers and Chemicals Ltd.", "Gujarat Narmada", "GNFC",
    "GPPL", "Gujarat Pipavav Port Ltd.", "Gujarat Pipavav", "Pipavav",
    "GSPL", "Gujarat State Petronet Ltd.", "Gujarat State Petronet", "GSPL",
     "HBLENGINE", "HBL Engineering Ltd.", "HBL Engineering", "HBL",
    "HCLTECH", "HCL Technologies Ltd.", "HCL Technologies", "HCL",
    "HDFCAMC", "HDFC Asset Management Company Ltd.", "HDFC AMC", "HDFC",
    "HDFCBANK", "HDFC Bank Ltd.", "HDFC Bank", "HDFC",
    "HDFCLIFE", "HDFC Life Insurance Company Ltd.", "HDFC Life", 
    "HFCL", "HFCL Ltd.", "HFCL",
    "HAPPSTMNDS", "Happiest Minds Technologies Ltd.", "Happiest Minds", "Happiest",
    "HAVELLS", "Havells India Ltd.", "Havells India", "Havells",
    "HEROMOTOCO", "Hero MotoCorp Ltd.", "Hero MotoCorp", "Hero",
    "HSCL", "Himadri Speciality Chemical Ltd.", "Himadri Speciality", "Himadri",
    "HINDALCO", "Hindalco Industries Ltd.", "Hindalco Industries", "Hindalco",
     "HAL", "Hindustan Aeronautics Ltd.", "Hindustan Aeronautics", 
    "HINDCOPPER", "Hindustan Copper Ltd.", "Hindustan Copper", "Hind Copper",
    "HINDPETRO", "Hindustan Petroleum Corporation Ltd.", "Hindustan Petroleum", "HPCL",
    "HINDUNILVR", "Hindustan Unilever Ltd.", "Hindustan Unilever", "HUL",
    "HINDZINC", "Hindustan Zinc Ltd.", "Hindustan Zinc", "Hind Zinc",
    "POWERINDIA", "Hitachi Energy India Ltd.", "Hitachi Energy", "Hitachi",
    "HOMEFIRST", "Home First Finance Company India Ltd.", "Home First Finance", "Home First",
    "HONASA", "Honasa Consumer Ltd.", "Honasa Consumer", "Honasa",
    "HONAUT", "Honeywell Automation India Ltd.", "Honeywell Automation", "Honeywell",
    "HUDCO", "Housing & Urban Development Corporation Ltd.", "HUDCO",
    "HYUNDAI", "Hyundai Motor India Ltd.", "Hyundai Motor", "Hyundai",
    "ICICIBANK", "ICICI Bank Ltd.", "ICICI Bank", 
    "ICICIGI", "ICICI Lombard General Insurance Company Ltd.", "ICICI Lombard", 
    "ICICIPRULI", "ICICI Prudential Life Insurance Company Ltd.", "ICICI Prudential", 
    "IDBI", "IDBI Bank Ltd.", "IDBI Bank", "IDBI",
    "IDFCFIRSTB", "IDFC First Bank Ltd.", "IDFC First Bank", "IDFC",
    "IFCI", "IFCI Ltd.", "IFCI",
    "IIFL", "IIFL Finance Ltd.", "IIFL Finance", "IIFL",
    "INOXINDIA", "INOX India Ltd.", "INOX India", "INOX",
    "IRB", "IRB Infrastructure Developers Ltd.", "IRB Infrastructure", "IRB",
    "IRCON", "IRCON International Ltd.", "IRCON International", "IRCON",
    "ITC", "ITC Ltd.", "ITC",
     "ITI Ltd.", 
    "INDGN", "Indegene Ltd.", "Indegene",
    "INDIACEM", "India Cements Ltd.", "India Cements", "India Cement",
    "INDIAMART", "Indiamart Intermesh Ltd.", "Indiamart Intermesh", "Indiamart",
    "INDIANB", "Indian Bank", "Indian Bank",
    "IEX", "Indian Energy Exchange Ltd.", "Indian Energy Exchange", "IEX",
    "INDHOTEL", "Indian Hotels Co. Ltd.", "Indian Hotels",
    "IOC", "Indian Oil Corporation Ltd.", "Indian Oil", "IOC",
    "IOB", "Indian Overseas Bank", "Indian Overseas Bank", "IOB",
    "IRCTC", "Indian Railway Catering And Tourism Corporation Ltd.", "IRCTC",
    "IRFC", "Indian Railway Finance Corporation Ltd.", "Indian Railway Finance", "IRFC",
    "IREDA", "Indian Renewable Energy Development Agency Ltd.", "IREDA",
    "IGL", "Indraprastha Gas Ltd.", "Indraprastha Gas", "IGL",
    "INDUSTOWER", "Indus Towers Ltd.", "Indus Towers", 
    "INDUSINDBK", "IndusInd Bank Ltd.", "IndusInd Bank", "IndusInd",
     "Info Edge (India) Ltd.", "Info Edge", 
    "INFY", "Infosys Ltd.", "Infosys", "INFY",
    "INOXWIND", "Inox Wind Ltd.", "Inox Wind", "Inox",
    "INTELLECT", "Intellect Design Arena Ltd.", "Intellect Design", "Intellect",
    "INDIGO", "InterGlobe Aviation Ltd.", "InterGlobe Aviation", "IndiGo",
    "IGIL", "International Gemmological Institute (India) Ltd.", "International Gemmological", "IGIL",
    "IKS", "Inventurus Knowledge Solutions Ltd.", "Inventurus Knowledge", "IKS",
    "IPCALAB", "Ipca Laboratories Ltd.", "Ipca Labs", "Ipca",
    "JBCHEPHARM", "J.B. Chemicals & Pharmaceuticals Ltd.", "J.B. Chemicals", "JB Pharma",
    "JKCEMENT", "J.K. Cement Ltd.", "J.K. Cement", "JK Cement",
    "JBMA", "JBM Auto Ltd.", "JBM Auto", "JBM",
    "JKTYRE", "JK Tyre & Industries Ltd.", "JK Tyre", 
    "JMFINANCIL", "JM Financial Ltd.", "JM Financial",
    "JSWENERGY", "JSW Energy Ltd.", "JSW Energy", 
    "JSWHL", "JSW Holdings Ltd.", "JSW Holdings", 
    "JSWINFRA", "JSW Infrastructure Ltd.", "JSW Infrastructure",
    "JSWSTEEL", "JSW Steel Ltd.", "JSW Steel", 
    "JPPOWER", "Jaiprakash Power Ventures Ltd.", "Jaiprakash Power", "JP Power",
    "J&KBANK", "Jammu & Kashmir Bank Ltd.", "Jammu & Kashmir Bank", "J&K Bank",
    "JINDALSAW", "Jindal Saw Ltd.", "Jindal Saw", "Jindal",
    "JSL", "Jindal Stainless Ltd.", "Jindal Stainless", "Jindal",
    "JINDALSTEL", "Jindal Steel & Power Ltd.", "Jindal Steel", "Jindal",
    "JIOFIN", "Jio Financial Services Ltd.", "Jio Financial", "Jio",
    "JUBLFOOD", "Jubilant Foodworks Ltd.", "Jubilant Foodworks", "Jubilant",
    "JUBLINGREA", "Jubilant Ingrevia Ltd.", "Jubilant Ingrevia", "Jubilant",
    "JUBLPHARMA", "Jubilant Pharmova Ltd.", "Jubilant Pharmova", "Jubilant",
    "JWL", "Jupiter Wagons Ltd.", "Jupiter Wagons", "Jupiter",
    "JUSTDIAL", "Justdial Ltd.", "Justdial",
    "JYOTHYLAB", "Jyothy Labs Ltd.", "Jyothy Labs", "Jyothy",
    "JYOTICNC", "Jyoti CNC Automation Ltd.", "Jyoti CNC", "Jyoti",
    "KPRMILL", "K.P.R. Mill Ltd.", "K.P.R. Mill", "KPR Mill",
    "KEI", "KEI Industries Ltd.", "KEI Industries", "KEI",
    "KNRCON", "KNR Constructions Ltd.", "KNR Constructions", "KNR",
    "KPITTECH", "KPIT Technologies Ltd.", "KPIT Technologies", "KPIT",
    "KAJARIACER", "Kajaria Ceramics Ltd.", "Kajaria Ceramics", "Kajaria",
    "KPIL", "Kalpataru Projects International Ltd.", "Kalpataru Projects", "Kalpataru",
    "KALYANKJIL", "Kalyan Jewellers India Ltd.", "Kalyan Jewellers", "Kalyan",
    "KANSAINER", "Kansai Nerolac Paints Ltd.", "Kansai Nerolac", "Nerolac",
    "KARURVYSYA", "Karur Vysya Bank Ltd.", "Karur Vysya Bank", "Karur",
    "KAYNES", "Kaynes Technology India Ltd.", "Kaynes Technology", "Kaynes",
    "KEC", "Kec International Ltd.", "Kec International", "KEC",
    "KFINTECH", "Kfin Technologies Ltd.", "Kfin Technologies", "Kfin",
    "KIRLOSBROS", "Kirloskar Brothers Ltd.", "Kirloskar Brothers", "Kirloskar",
    "KIRLOSENG", "Kirloskar Oil Eng Ltd.", "Kirloskar Oil", "Kirloskar",
    "KOTAKBANK", "Kotak Mahindra Bank Ltd.", "Kotak Mahindra Bank", "Kotak",
    "KIMS", "Krishna Institute of Medical Sciences Ltd.", "Krishna Institute", "KIMS",
    "LTF", "L&T Finance Ltd.", "L&T Finance", "LTF",
    "LTTS", "L&T Technology Services Ltd.", "L&T Technology", "LTTS",
    "LICHSGFIN", "LIC Housing Finance Ltd.", "LIC Housing",
    "LTFOODS", "LT Foods Ltd.", "LT Foods",
    "LTIM", "LTIMindtree Ltd.", "LTIMindtree", "LTIM",
     "Larsen & Toubro Ltd.", "Larsen & Toubro", "L&T",
    "LATENTVIEW", "Latent View Analytics Ltd.", "Latent View", "Latent",
    "LAURUSLABS", "Laurus Labs Ltd.", "Laurus Labs", "Laurus",
    "LEMONTREE", "Lemon Tree Hotels Ltd.", "Lemon Tree Hotels", "Lemon Tree",
    "LICI", "Life Insurance Corporation of India", "LIC India",
    "LINDEINDIA", "Linde India Ltd.", "Linde India", "Linde",
    "LLOYDSME", "Lloyds Metals And Energy Ltd.", "Lloyds Metals", "Lloyds",
    "LUPIN", "Lupin Ltd.", "Lupin",
    "MMTC", "MMTC Ltd.", "MMTC",
    "MRF", "MRF Ltd.", "MRF",
    "LODHA", "Macrotech Developers Ltd.", "Macrotech Developers", "Lodha",
    "MGL", "Mahanagar Gas Ltd.", "Mahanagar Gas", "MGL",
    "MAHSEAMLES", "Maharashtra Seamless Ltd.", "Maharashtra Seamless", "Mah Seamless",
    "M&MFIN", "Mahindra & Mahindra Financial Services Ltd.", "Mahindra Financial", "M&M Financial",
    "M&M", "Mahindra & Mahindra Ltd.", "Mahindra & Mahindra", "Mahindra",
    "MANAPPURAM", "Manappuram Finance Ltd.", "Manappuram Finance", "Manappuram",
    "MRPL", "Mangalore Refinery & Petrochemicals Ltd.", "Mangalore Refinery", "MRPL",
    "MANKIND", "Mankind Pharma Ltd.", "Mankind Pharma", "Mankind",
    "MARICO", "Marico Ltd.", "Marico",
    "MARUTI", "Maruti Suzuki India Ltd.", "Maruti Suzuki", "Maruti",
    "MASTEK", "Mastek Ltd.", "Mastek",
    "MFSL", "Max Financial Services Ltd.", "Max Financial", 
    "MAXHEALTH", "Max Healthcare Institute Ltd.", "Max Healthcare", 
    "MAZDOCK", "Mazagoan Dock Shipbuilders Ltd.", "Mazagoan Dock", "Mazagon",
    "METROPOLIS", "Metropolis Healthcare Ltd.", "Metropolis Healthcare", "Metropolis",
    "MINDACORP", "Minda Corporation Ltd.", "Minda Corporation", "Minda",
    "MSUMI", "Motherson Sumi Wiring India Ltd.", "Motherson Sumi", "Motherson",
    "MOTILALOFS", "Motilal Oswal Financial Services Ltd.", "Motilal Oswal", "Motilal",
    "MPHASIS", "MphasiS Ltd.", "MphasiS",
    "MCX", "Multi Commodity Exchange of India Ltd.", "Multi Commodity Exchange", "MCX",
    "MUTHOOTFIN", "Muthoot Finance Ltd.", "Muthoot Finance", "Muthoot",
    "NATCOPHARM", "NATCO Pharma Ltd.", "NATCO Pharma", "NATCO",
    "NBCC", "NBCC (India) Ltd.", "NBCC India", "NBCC",
    "NCC", "NCC Ltd.", "NCC",
    "NHPC", "NHPC Ltd.", "NHPC",
    "NLCINDIA", "NLC India Ltd.", "NLC India", "NLC",
    "NMDC", "NMDC Ltd.", "NMDC",
    "NSLNISP", "NMDC Steel Ltd.", "NMDC Steel", "NMDC",
    "NTPCGREEN", "NTPC Green Energy Ltd.", "NTPC Green", "NTPC",
    "NTPC", "NTPC Ltd.", "NTPC",
     "Narayana Hrudayalaya Ltd.", "Narayana Hrudayalaya", "Narayana",
    "NATIONALUM", "National Aluminium Co. Ltd.", "National Aluminium", "NALCO",
    "NAVA", "Nava Ltd.", "Nava",
    "NAVINFLUOR", "Navin Fluorine International Ltd.", "Navin Fluorine", "Navin",
    "NESTLEIND", "Nestle India Ltd.", "Nestle India", "Nestle",
    "NETWEB", "Netweb Technologies India Ltd.", "Netweb Technologies", "Netweb",
    "NETWORK18", "Network18 Media & Investments Ltd.", "Network18 Media", "Network18",
    "NEULANDLAB", "Neuland Laboratories Ltd.", "Neuland Laboratories", "Neuland",
    "NEWGEN", "Newgen Software Technologies Ltd.", "Newgen Software", "Newgen",
    "NAM-INDIA", "Nippon Life India Asset Management Ltd.", "Nippon Life", "Nippon",
    "NIVABUPA", "Niva Bupa Health Insurance Company Ltd.", "Niva Bupa", "Niva",
    "NUVAMA", "Nuvama Wealth Management Ltd.", "Nuvama Wealth", "Nuvama",
    "OBEROIRLTY", "Oberoi Realty Ltd.", "Oberoi Realty", "Oberoi",
    "OIL", "Oil India Ltd.", "Oil India", "OIL",
    "ONGC", "Oil & Natural Gas Corporation Ltd.", "ONGC", "Oil & Natural Gas",
    "OLECTRA", "Olectra Greentech Ltd.", "Olectra Greentech", "Olectra",
    "OFSS", "Oracle Financial Services Software Ltd.", "Oracle Financial", "OFSS",
    "POLICYBZR", "PB Fintech Ltd.", "PB Fintech", "Policybazaar",
    "PCBL", "PCBL Chemical Ltd.", "PCBL Chemical", "PCBL",
    "PGEL", "PG Electroplast Ltd.", "PG Electroplast", "PGEL",
    "PIIND", "PI Industries Ltd.", "PI Industries",
    "PNBHOUSING", "PNB Housing Finance Ltd.", "PNB Housing", "PNB",
    "PNCINFRA", "PNC Infratech Ltd.", "PNC Infratech", "PNC",
    "PTCIL", "PTC Industries Ltd.", "PTC Industries", "PTC",
    "PVRINOX", "PVR INOX Ltd.", "PVR INOX", 
    "PAGEIND", "Page Industries Ltd.", "Page Industries", 
    "PATANJALI", "Patanjali Foods Ltd.", "Patanjali Foods", "Patanjali",
    "PERSISTENT", "Persistent Systems Ltd.", "Persistent Systems", "Persistent",
    "PETRONET", "Petronet LNG Ltd.", "Petronet LNG", "Petronet",
    "PFIZER", "Pfizer Ltd.", "Pfizer",
    "PHOENIXLTD", "Phoenix Mills Ltd.", "Phoenix Mills", "Phoenix",
    "PIDILITIND", "Pidilite Industries Ltd.", "Pidilite Industries", "Pidilite",
    "PIRAMAL", "Piramal Enterprises Ltd.", "Piramal Enterprises", "Piramal",
    "PPLPHARMA", "Piramal Pharma Ltd.", "Piramal Pharma", "Piramal",
    "POLYMED", "Poly Medicure Ltd.", "Poly Medicure", "Polymed",
    "POLYCAB", "Polycab India Ltd.", "Polycab India", "Polycab",
    "POONAWALLA", "Poonawalla Fincorp Ltd.", "Poonawalla Fincorp", "Poonawalla",
    "PFC", "Power Finance Corporation Ltd.", "Power Finance", "PFC",
    "POWERGRID", "Power Grid Corporation of India Ltd.", "Power Grid", "PowerGrid",
    "PRAJIND", "Praj Industries Ltd.", "Praj Industries", "Praj",
    "PREMIERENE", "Premier Energies Ltd.", "Premier Energies", "Premier",
    "PRESTIGE", "Prestige Estates Projects Ltd.", "Prestige Estates", "Prestige",
    "PNB", "Punjab National Bank", "Punjab National Bank", "PNB",
    "RRKABEL", "R R Kabel Ltd.", "R R Kabel", "RR Kabel",
    "RBLBANK", "RBL Bank Ltd.", "RBL Bank", "RBL",
    "RECLTD", "REC Ltd.", 
    "RHIM", "RHI MAGNESITA INDIA LTD.", "RHI Magnesita", "RHI",
    "RITES", "RITES Ltd.", "RITES",
    "RADICO", "Radico Khaitan Ltd.", "Radico Khaitan", "Radico",
    "RVNL", "Rail Vikas Nigam Ltd.", "Rail Vikas", "RVNL",
    "RAILTEL", "Railtel Corporation Of India Ltd.", "Railtel Corporation", "Railtel",
    "RAINBOW", "Rainbow Childrens Medicare Ltd.", "Rainbow Childrens", "Rainbow",
    "RKFORGE", "Ramkrishna Forgings Ltd.", "Ramkrishna Forgings", "RK Forge",
    "RCF", "Rashtriya Chemicals & Fertilizers Ltd.", "Rashtriya Chemicals", "RCF",
    "RTNINDIA", "RattanIndia Enterprises Ltd.", "RattanIndia Enterprises", "RattanIndia",
    "RAYMONDLSL", "Raymond Lifestyle Ltd.", "Raymond Lifestyle", "Raymond",
    "RAYMOND", "Raymond Ltd.", "Raymond",
    "REDINGTON", "Redington Ltd.", "Redington",
    "RELIANCE", "Reliance Industries Ltd.", "Reliance Industries", "Reliance",
    "RPOWER", "Reliance Power Ltd.", "Reliance Power", "Reliance",
     "Route Mobile Ltd.", "Route Mobile", 
    "SBFC", "SBFC Finance Ltd.", "SBFC Finance", "SBFC",
    "SBICARD", "SBI Cards and Payment Services Ltd.", "SBI Cards", "SBI",
    "SBILIFE", "SBI Life Insurance Company Ltd.", "SBI Life", "SBI",
    "SJVN", "SJVN Ltd.", "SJVN",
    "SKFINDIA", "SKF India Ltd.", "SKF India", "SKF",
    "SAGILITY", "Sagility India Ltd.", "Sagility India", "Sagility",
    "SAILIFE", "Sai Life Sciences Ltd.", "Sai Life Sciences", "Sai Life",
    "SAMMAANCAP", "Sammaan Capital Ltd.", "Sammaan Capital", "Sammaan",
    "MOTHERSON", "Samvardhana Motherson International Ltd.", "Samvardhana Motherson", "Motherson",
    "SAPPHIRE", "Sapphire Foods India Ltd.", "Sapphire Foods", "Sapphire",
    "SARDAEN", "Sarda Energy and Minerals Ltd.", "Sarda Energy", "Sarda",
    "SAREGAMA", "Saregama India Ltd.", "Saregama India", "Saregama",
    "SCHAEFFLER", "Schaeffler India Ltd.", "Schaeffler India", "Schaeffler",
    "SCHNEIDER", "Schneider Electric Infrastructure Ltd.", "Schneider Electric", "Schneider",
     "Shipping Corporation of India Ltd.", "Shipping Corporation",
    "SHREECEM", "Shree Cement Ltd.", "Shree Cement", "Shree",
    "RENUKA", "Shree Renuka Sugars Ltd.", "Shree Renuka", "Renuka",
    "SHRIRAMFIN", "Shriram Finance Ltd.", "Shriram Finance", "Shriram",
    "SHYAMMETL", "Shyam Metalics and Energy Ltd.", "Shyam Metalics", "Shyam",
    "SIEMENS", "Siemens Ltd.", "Siemens",
    "SIGNATURE", "Signatureglobal (India) Ltd.", "Signatureglobal", "Signature",
    "SOBHA", "Sobha Ltd.", "Sobha",
    "SOLARINDS", "Solar Industries India Ltd.", "Solar Industries", 
    "SONACOMS", "Sona BLW Precision Forgings Ltd.", "Sona BLW", 
    "SONATSOFTW", "Sonata Software Ltd.", "Sonata Software", "Sonata",
    "STARHEALTH", "Star Health and Allied Insurance Company Ltd.", "Star Health",
    "SBIN", "State Bank of India", "State Bank", "SBI",
    "SAIL", "Steel Authority of India Ltd.", "Steel Authority", "SAIL",
    "SWSOLAR", "Sterling and Wilson Renewable Energy Ltd.", "Sterling Wilson", "SWSolar",
    "SUMICHEM", "Sumitomo Chemical India Ltd.", "Sumitomo Chemical", "Sumichem",
    "SUNPHARMA", "Sun Pharmaceutical Industries Ltd.", "Sun Pharma", 
    "SUNTV", "Sun TV Network Ltd.", "Sun TV", 
    "SUNDARMFIN", "Sundaram Finance Ltd.", "Sundaram Finance", "Sundaram",
    "SUNDRMFAST", "Sundram Fasteners Ltd.", "Sundram Fasteners", "Sundram",
    "SUPREMEIND", "Supreme Industries Ltd.", "Supreme Industries", 
    "SUVENPHAR", "Suven Pharmaceuticals Ltd.", "Suven Pharma", "Suven",
    "SUZLON", "Suzlon Energy Ltd.", "Suzlon Energy", "Suzlon",
    "SWANENERGY", "Swan Energy Ltd.", "Swan Energy", "Swan",
    "SWIGGY", "Swiggy Ltd.", "Swiggy",
    "SYNGENE", "Syngene International Ltd.", "Syngene International", "Syngene",
    "SYRMA", "Syrma SGS Technology Ltd.", "Syrma SGS", "Syrma",
    "TBOTEK", "TBO Tek Ltd.", "TBO Tek", "TBO",
    "TVSMOTOR", "TVS Motor Company Ltd.", "TVS Motor", "TVS",
    "TANLA", "Tanla Platforms Ltd.", "Tanla Platforms", "Tanla",
    "TATACHEM", "Tata Chemicals Ltd.", "Tata Chemicals", 
    "TATACOMM", "Tata Communications Ltd.", "Tata Communications",
    "TCS", "Tata Consultancy Services Ltd.", "Tata Consultancy", "TCS",
    "TATACONSUM", "Tata Consumer Products Ltd.", "Tata Consumer", 
    "TATAELXSI", "Tata Elxsi Ltd.", "Tata Elxsi", 
    "TATAINVEST", "Tata Investment Corporation Ltd.", "Tata Investment", 
    "TATAMOTORS", "Tata Motors Ltd.", "Tata Motors",
    "TATAPOWER", "Tata Power Co. Ltd.", "Tata Power", 
    "TATASTEEL", "Tata Steel Ltd.", "Tata Steel", 
    "TATATECH", "Tata Technologies Ltd.", "Tata Technologies", 
    "TTML", "Tata Teleservices (Maharashtra) Ltd.", "Tata Teleservices", 
    "TECHM", "Tech Mahindra Ltd.", "Tech Mahindra", "TechM",
    "TECHNOE", "Techno Electric & Engineering Company Ltd.", "Techno Electric",
    "TEJASNET", "Tejas Networks Ltd.", "Tejas Networks", 
    "TEMBO", "Tembo Global Industries Ltd.", "Tembo Global", "Tembo",
    "THERMAX", "Thermax Ltd.", "Thermax",
    "TIMKEN", "Timken India Ltd.", "Timken India", "Timken",
    "TITAN", "Titan Company Ltd.", "Titan Company", "Titan",
    "TORNTPHARM", "Torrent Pharmaceuticals Ltd.", "Torrent Pharma", 
    "TORNTPOWER", "Torrent Power Ltd.", "Torrent Power", 
    "TRENT", "Trent Ltd.", "Trent",
    "TRIDENT", "Trident Ltd.", "Trident",
    "TRIVENI", "Triveni Engineering & Industries Ltd.", "Triveni Engineering", "Triveni",
    "TRITURBINE", "Triveni Turbine Ltd.", "Triveni Turbine", "Triveni",
    "TIINDIA", "Tube Investments of India Ltd.", "Tube Investments",
    "UCOBANK", "UCO Bank", "UCO Bank", "UCO",
    "UNIONBANK", "Union Bank of India", "Union Bank", "UBI",
    "UBL", "United Breweries Ltd.", "United Breweries", "UBL",
    "MCDOWELL-N", "United Spirits Ltd.", "United Spirits", "McDowell",
    "UNITDSPR", "United Springs Ltd.", "United Springs", "Unitdspr",
    "UPL Ltd.",
    "UTIAMC",
    "VGUARD", "V-Guard Industries Ltd.", "V-Guard Industries", "V-Guard",
    "VMART", "V-Mart Retail Ltd.", "V-Mart Retail", "V-Mart",
    "VIPIND", "VIP Industries Ltd.", "VIP Industries",
    "VAIBHAVGBL", "Vaibhav Global Ltd.", "Vaibhav Global", "Vaibhav",
    "VBL", "Varun Beverages Ltd.", "Varun Beverages", "VBL",
    "VSTIND", "VST Industries Ltd.", "VST Industries", "VST",
    "WELCORP", "Welspun Corp Ltd.", "Welspun Corp", "Welspun",
    "WELSPUNLIV", "Welspun Living Ltd.", "Welspun Living", "Welspun",
    "WESTLIFE", "Westlife Foodworld Ltd.", "Westlife Foodworld", "Westlife",
    "WHIRLPOOL", "Whirlpool of India Ltd.", "Whirlpool India", "Whirlpool",
    "WIPRO", "Wipro Ltd.", "Wipro",
    "YESBANK", "Yes Bank Ltd.", "Yes Bank",
    "ZEELEARN", "Zee Learn Ltd.", "Zee Learn", "Zee",
    "ZEEL", "Zee Entertainment Enterprises Ltd.", "Zee Entertainment", "Zee",
    "ZENSARTECH", "Zensar Technologies Ltd.", "Zensar Technologies", "Zensar",
    "ZOMATO", "Zomato Ltd.", "Zomato",
    "ZYDUSLIFE", "Zydus Lifesciences Ltd.", "Zydus Lifesciences", "Zydus",
    "ECLERX", "eClerx Services Ltd.", "eClerx Services", "eClerx",
   
]

# Company name to NSE symbol mapping
COMPANY_SYMBOL_MAP = {
    "HDFCBANK": ["HDFC Bank Ltd.", "HDFC Bank", "HDFC", "HDFCBANK"],
    "RELIANCE": ["Reliance Industries Ltd.", "Reliance Industries", "Reliance", "RELIANCE"],
    "INFY": ["Infosys Ltd.", "Infosys", "INFY"],
    "TCS": ["Tata Consultancy Services Ltd.", "Tata Consultancy", "TCS"],
    "ICICIBANK": ["ICICI Bank Ltd.", "ICICI Bank"],
    "HINDUNILVR": ["Hindustan Unilever Ltd.", "Hindustan Unilever", "HUL", "HINDUNILVR"],
    "ITC": ["ITC Ltd.", "ITC"],
    "SBIN": ["State Bank of India", "State Bank", "SBI", "SBIN"],
    "BHARTIARTL": ["Bharti Airtel Ltd.", "Bharti Airtel", "Airtel", "BHARTIARTL"],
    "KOTAKBANK": ["Kotak Mahindra Bank Ltd.", "Kotak Mahindra Bank", "Kotak Bank", "KOTAKBANK"],
    "ASIANPAINT": ["Asian Paints Ltd.", "Asian Paints", "ASIANPAINT"],
    "AXISBANK": ["Axis Bank Ltd.", "Axis Bank", "AXISBANK"],
    "MARUTI": ["Maruti Suzuki India Ltd.", "Maruti Suzuki", "Maruti", "MARUTI"],
    "ULTRACEMCO": ["UltraTech Cement Ltd.", "UltraTech Cement", "UltraTech", "ULTRACEMCO"],
    "TITAN": ["Titan Company Ltd.", "Titan Company", "Titan", "TITAN"],
    "NESTLEIND": ["Nestle India Ltd.", "Nestle India", "Nestle", "NESTLEIND"],
    "ONGC": ["Oil & Natural Gas Corporation Ltd.", "ONGC"],
    "POWERGRID": ["Power Grid Corporation of India Ltd.", "Power Grid", "POWERGRID"],
    "NTPC": ["NTPC Ltd.", "NTPC"],
    "TECHM": ["Tech Mahindra Ltd.", "Tech Mahindra", "TechM", "TECHM"],
    "WIPRO": ["Wipro Ltd.", "Wipro", "WIPRO"],
    "SUNPHARMA": ["Sun Pharmaceutical Industries Ltd.", "Sun Pharma", "SUNPHARMA"],
    "TATASTEEL": ["Tata Steel Ltd.", "Tata Steel", "TATASTEEL"],
    "BAJAJ-AUTO": ["Bajaj Auto Ltd.", "Bajaj Auto", "BAJAJ-AUTO"],
    "HEROMOTOCO": ["Hero MotoCorp Ltd.", "Hero MotoCorp", "Hero", "HEROMOTOCO"],
    "COALINDIA": ["Coal India Ltd.", "Coal India", "COALINDIA"],
    "JSWSTEEL": ["JSW Steel Ltd.", "JSW Steel", "JSWSTEEL"],
    "TATAMOTORS": ["Tata Motors Ltd.", "Tata Motors", "TATAMOTORS"],
    "BRITANNIA": ["Britannia Industries Ltd.", "Britannia Industries", "Britannia", "BRITANNIA"],
    "SHREECEM": ["Shree Cement Ltd.", "Shree Cement", "SHREECEM"],
    "INDUSINDBK": ["IndusInd Bank Ltd.", "IndusInd Bank", "IndusInd", "INDUSINDBK"],
    "CIPLA": ["Cipla Ltd.", "Cipla", "CIPLA"],
    "DRREDDY": ["Dr. Reddy's Laboratories Ltd.", "Dr. Reddy's", "Dr. Reddy", "DRREDDY"],
    "EICHERMOT": ["Eicher Motors Ltd.", "Eicher Motors", "Eicher", "EICHERMOT"],
    "GRASIM": ["Grasim Industries Ltd.", "Grasim Industries", "Grasim", "GRASIM"],
    "HCLTECH": ["HCL Technologies Ltd.", "HCL Technologies", "HCL", "HCLTECH"],
    "HDFCLIFE": ["HDFC Life Insurance Company Ltd.", "HDFC Life", "HDFCLIFE"],
    "HINDALCO": ["Hindalco Industries Ltd.", "Hindalco Industries", "Hindalco", "HINDALCO"],
    "IOC": ["Indian Oil Corporation Ltd.", "Indian Oil", "IOC"],
    "M&M": ["Mahindra & Mahindra Ltd.", "Mahindra & Mahindra", "Mahindra", "M&M"],
    "TATACONSUM": ["Tata Consumer Products Ltd.", "Tata Consumer", "TATACONSUM"],
    "BPCL": ["Bharat Petroleum Corporation Ltd.", "Bharat Petroleum", "BPCL"],
    "DIVISLAB": ["Divi's Laboratories Ltd.", "Divi's Laboratories", "DIVISLAB"],
    "ADANIPORTS": ["Adani Ports and Special Economic Zone Ltd.", "Adani Ports", "ADANIPORTS"],
    "360ONE": ["360 ONE WAM Ltd.", "360 ONE", "360 ONE WAM", "360ONE"],
    "3MINDIA": ["3M India Ltd.", "3M India", "3MINDIA"],
    "ABB": ["ABB India Ltd.", "ABB India", "ABB"],
    "ACMESOLAR": ["ACME Solar Holdings Ltd.", "ACME Solar", "ACME"],
    "AIAENG": ["AIA Engineering Ltd.", "AIA Engineering", "AIA"],
    "APLAPOLLO": ["APL Apollo Tubes Ltd.", "APL Apollo", "Apollo Tubes"],
    "AUBANK": ["AU Small Finance Bank Ltd.", "AU Small Finance", "AU Bank"],
    "AWL": ["AWL Agri Business Ltd.", "AWL Agri", "AWL"],
    "AADHARHFC": ["Aadhar Housing Finance Ltd.", "Aadhar Housing", "Aadhar"],
    "AARTIIND": ["Aarti Industries Ltd.", "Aarti Industries", "Aarti"],
    "AAVAS": ["Aavas Financiers Ltd.", "Aavas Financiers", "Aavas"],
    "ABBOTINDIA": ["Abbott India Ltd.", "Abbott India", "Abbott"],
    "ADANIENSOL": ["Adani Energy Solutions Ltd.", "Adani Energy"],
    "ADANIENT": ["Adani Enterprises Ltd.", "Adani Enterprises"],
    "ADANIGREEN": ["Adani Green Energy Ltd.", "Adani Green"],
    "ADANIPOWER": ["Adani Power Ltd.", "Adani Power"],
    "ATGL": ["Adani Total Gas Ltd.", "Adani Total Gas"],
    "ABCAPITAL": ["Aditya Birla Capital Ltd.", "Aditya Birla Capital"],
    "ABFRL": ["Aditya Birla Fashion and Retail Ltd.", "Aditya Birla Fashion"],
    "ABREL": ["Aditya Birla Real Estate Ltd.", "Aditya Birla Real Estate"],
    "ABSLAMC": ["Aditya Birla Sun Life AMC Ltd.", "Aditya Birla Sun Life"],
    "AEGISLOG": ["Aegis Logistics Ltd.", "Aegis Logistics", "Aegis"],
    "AFCONS": ["Afcons Infrastructure Ltd.", "Afcons Infrastructure", "Afcons"],
    "AFFLE": ["Affle 3i Ltd.", "Affle 3i", "Affle"],
    "AJANTPHARM": ["Ajanta Pharmaceuticals Ltd.", "Ajanta Pharma", "Ajanta"],
    "AKUMS": ["Akums Drugs and Pharmaceuticals Ltd.", "Akums Drugs", "Akums"],
    "APLLTD": ["Alembic Pharmaceuticals Ltd.", "Alembic Pharma", "Alembic"],
    "ALIVUS": ["Alivus Life Sciences Ltd.", "Alivus Life Sciences", "Alivus"],
    "ALKEM": ["Alkem Laboratories Ltd.", "Alkem Labs", "Alkem"],
    "ALKYLAMINE": ["Alkyl Amines Chemicals Ltd.", "Alkyl Amines"],
    "ALOKINDS": ["Alok Industries Ltd.", "Alok Industries"],
    "ARE&M": ["Amara Raja Energy & Mobility Ltd.", "Amara Raja", "Amara"],
    "AMBER": ["Amber Enterprises India Ltd.", "Amber Enterprises"],
    "AMBUJACEM": ["Ambuja Cements Ltd.", "Ambuja Cements", "Ambuja"],
    "ANANDRATHI": ["Anand Rathi Wealth Ltd.", "Anand Rathi"],
    "ANANTRAJ": ["Anant Raj Ltd.", "Anant Raj"],
    "ANGELONE": ["Angel One Ltd.", "Angel One"],
    "APARINDS": ["Apar Industries Ltd.", "Apar Industries"],
    "APOLLOHOSP": ["Apollo Hospitals Enterprise Ltd.", "Apollo Hospitals"],
    "APOLLOTYRE": ["Apollo Tyres Ltd.", "Apollo Tyres"],
    "APTUS": ["Aptus Value Housing Finance India Ltd.", "Aptus Value Housing", "Aptus"],
    "ASAHIINDIA": ["Asahi India Glass Ltd.", "Asahi India", "Asahi"],
    "ASHOKLEY": ["Ashok Leyland Ltd.", "Ashok Leyland"],
    "ASIANPAINT": ["Asian Paints Ltd.", "Asian Paints"],
    "ASTERDM": ["Aster DM Healthcare Ltd.", "Aster DM", "Aster"],
    "ASTRAZEN": ["AstraZenca Pharma India Ltd.", "AstraZenca Pharma", "AstraZenca"],
    "ASTRAL": ["Astral Ltd.", "Astral"],
    "ATUL": ["Atul Ltd.", "Atul"],
    "AUROPHARMA": ["Aurobindo Pharma Ltd.", "Aurobindo Pharma", "Aurobindo"],
    "AIIL": ["Authum Investment & Infrastructure Ltd.", "Authum Investment", "Authum"],
    "DMART": ["Avenue Supermarts Ltd.", "Avenue Supermarts", "DMart"],
    "AXISBANK": ["Axis Bank Ltd.", "Axis Bank"],
    "BASF": ["BASF India Ltd.", "BASF India", "BASF"],
    "BEML": ["BEML Ltd.", "BEML"],
    "BLS": ["BLS International Services Ltd.", "BLS International", "BLS"],
    "BSE": ["BSE Ltd.", "BSE"],
    "BAJAJ-AUTO": ["Bajaj Auto Ltd.", "Bajaj Auto"],
    "BAJFINANCE": ["Bajaj Finance Ltd.", "Bajaj Finance"],
    "BAJAJFINSV": ["Bajaj Finserv Ltd.", "Bajaj Finserv"],
    "BAJAJHLDNG": ["Bajaj Holdings & Investment Ltd.", "Bajaj Holdings"],
    "BAJAJHFL": ["Bajaj Housing Finance Ltd.", "Bajaj Housing"],
    "BALKRISIND": ["Balkrishna Industries Ltd.", "Balkrishna Industries", "Balkrishna"],
    "BALRAMCHIN": ["Balrampur Chini Mills Ltd.", "Balrampur Chini", "Balrampur"],
    "BANDHANBNK": ["Bandhan Bank Ltd.", "Bandhan Bank", "Bandhan"],
    "BANKBARODA": ["Bank of Baroda", "Bank of Baroda", "BOB"],
    "BANKINDIA": ["Bank of India", "Bank of India", "BOI"],
    "MAHABANK": ["Bank of Maharashtra", "Bank of Maharashtra", "Mahabank"],
    "BATAINDIA": ["Bata India Ltd.", "Bata India", "Bata"],
    "BAYERCROP": ["Bayer Cropscience Ltd.", "Bayer Cropscience", "Bayer"],
    "BERGEPAINT": ["Berger Paints India Ltd.", "Berger Paints", "Berger"],
    "BDL": ["Bharat Dynamics Ltd.", "Bharat Dynamics"],
    "BEL": ["Bharat Electronics Ltd.", "Bharat Electronics"],
    "BHARATFORG": ["Bharat Forge Ltd.", "Bharat Forge"],
    "BHEL": ["Bharat Heavy Electricals Ltd.", "Bharat Heavy Electricals"],
    "BPCL": ["Bharat Petroleum Corporation Ltd.", "Bharat Petroleum", "BPCL"],
    "BHARTIARTL": ["Bharti Airtel Ltd.", "Bharti Airtel"],
    "BHARTIHEXA": ["Bharti Hexacom Ltd.", "Bharti Hexacom", "Hexacom"],
    "BIKAJI": ["Bikaji Foods International Ltd.", "Bikaji Foods", "Bikaji"],
    "BIOCON": ["Biocon Ltd.", "Biocon"],
    "BSOFT": ["Birlasoft Ltd.", "Birlasoft", "BSOFT"],
    "BLUEDART": ["Blue Dart Express Ltd.", "Blue Dart"],
    "BLUESTARCO": ["Blue Star Ltd.", "Blue Star"],
    "BBTC": ["Bombay Burmah Trading Corporation Ltd.", "Bombay Burmah", "BBTC"],
    "BOSCHLTD": ["Bosch Ltd.", "Bosch"],
    "FIRSTCRY": ["Brainbees Solutions Ltd.", "Brainbees", "FirstCry"],
    "BRIGADE": ["Brigade Enterprises Ltd.", "Brigade Enterprises", "Brigade"],
    "BRITANNIA": ["Britannia Industries Ltd.", "Britannia Industries", "Britannia"],
    "MAPMYINDIA": ["C.E. Info Systems Ltd.", "C.E. Info Systems", "MapmyIndia"],
    "CCL": ["CCL Products (I) Ltd.", "CCL Products", "CCL"],
    "CESC": ["CESC Ltd.", "CESC"],
    "CGPOWER": ["CG Power and Industrial Solutions Ltd.", "CG Power", "CG"],
    "CRISIL": ["CRISIL Ltd.", "CRISIL"],
    "CAMPUS": ["Campus Activewear Ltd.", "Campus Activewear", "Campus"],
    "CANFINHOME": ["Can Fin Homes Ltd.", "Can Fin Homes", "Can Fin"],
    "CANBK": ["Canara Bank", "Canara Bank", "Canara"],
    "CAPLIPOINT": ["Caplin Point Laboratories Ltd.", "Caplin Point", "Caplin"],
    "CGCL": ["Capri Global Capital Ltd.", "Capri Global", "Capri"],
    "CARBORUNIV": ["Carborundum Universal Ltd.", "Carborundum Universal", "Carborundum"],
    "CASTROLIND": ["Castrol India Ltd.", "Castrol India", "Castrol"],
    "CEATLTD": ["Ceat Ltd.", "Ceat"],
    "CENTRALBK": ["Central Bank of India", "Central Bank", "CBI"],
    "CDSL": ["Central Depository Services (India) Ltd.", "Central Depository Services", "CDSL"],
    "CENTURYPLY": ["Century Plyboards (India) Ltd.", "Century Plyboards", "Century"],
    "CERA": ["Cera Sanitaryware Ltd.", "Cera Sanitaryware", "Cera"],
    "CHALET": ["Chalet Hotels Ltd.", "Chalet Hotels", "Chalet"],
    "CHAMBLFERT": ["Chambal Fertilizers & Chemicals Ltd.", "Chambal Fertilizers", "Chambal"],
    "CHENNPETRO": ["Chennai Petroleum Corporation Ltd.", "Chennai Petroleum", "CPCL"],
    "CHOLAHLDNG": ["Cholamandalam Financial Holdings Ltd.", "Cholamandalam Financial", "Cholamandalam"],
    "CHOLAFIN": ["Cholamandalam Investment and Finance Company Ltd.", "Cholamandalam Investment", "Cholamandalam"],
    "CIPLA": ["Cipla Ltd.", "Cipla"],
    "CUB": ["City Union Bank Ltd.", "City Union Bank", "CUB"],
    "CLEAN": ["Clean Science and Technology Ltd.", "Clean Science"],
    "COALINDIA": ["Coal India Ltd.", "Coal India"],
    "COCHINSHIP": ["Cochin Shipyard Ltd.", "Cochin Shipyard", "Cochin"],
    "COFORGE": ["Coforge Ltd.", "Coforge"],
    "COLPAL": ["Colgate Palmolive (India) Ltd.", "Colgate Palmolive", "Colgate"],
    "CAMS": ["Computer Age Management Services Ltd.", "Computer Age Management", "CAMS"],
    "CONCORDBIO": ["Concord Biotech Ltd.", "Concord Biotech", "Concord"],
    "CONCOR": ["Container Corporation of India Ltd.", "Container Corporation", "Concor"],
    "COROMANDEL": ["Coromandel International Ltd.", "Coromandel International", "Coromandel"],
    "CRAFTSMAN": ["Craftsman Automation Ltd.", "Craftsman Automation", "Craftsman"],
    "CREDITACC": ["CreditAccess Grameen Ltd.", "CreditAccess Grameen", "CreditAccess"],
    "CROMPTON": ["Crompton Greaves Consumer Electricals Ltd.", "Crompton Greaves", "Crompton"],
    "CUMMINSIND": ["Cummins India Ltd.", "Cummins India", "Cummins"],
    "CYIENT": ["Cyient Ltd.", "Cyient"],
    "DCMSHRIRAM": ["DCM Shriram Ltd.", "DCM Shriram", "DCM"],
    "DLF": ["DLF Ltd.", "DLF"],
    "DOMS": ["DOMS Industries Ltd.", "DOMS Industries", "DOMS"],
    "DABUR": ["Dabur India Ltd.", "Dabur India", "Dabur"],
    "DALBHARAT": ["Dalmia Bharat Ltd.", "Dalmia Bharat", "Dalmia"],
    "DATAPATTNS": ["Data Patterns (India) Ltd.", "Data Patterns"],
    "DEEPAKFERT": ["Deepak Fertilisers & Petrochemicals Corp. Ltd.", "Deepak Fertilisers", "Deepak"],
    "DEEPAKNTR": ["Deepak Nitrite Ltd.", "Deepak Nitrite"],
    "DELHIVERY": ["Delhivery Ltd.", "Delhivery"],
    "DEVYANI": ["Devyani International Ltd.", "Devyani International"],
    "DIVISLAB": ["Divi's Laboratories Ltd.", "Divi's Laboratories"],
    "DIXON": ["Dixon Technologies (India) Ltd.", "Dixon Technologies", "Dixon"],
    "LALPATHLAB": ["Dr. Lal Path Labs Ltd.", "Dr. Lal Path Labs", "Lal Path"],
    "DRREDDY": ["Dr. Reddy's Laboratories Ltd.", "Dr. Reddy's", "Dr. Reddy"],
    "DUMMYSIEMS": ["Dummy Siemens Ltd.", "Dummy Siemens", "Siemens"],
    "EIDPARRY": ["E.I.D. Parry (India) Ltd.", "E.I.D. Parry", "EIDPARRY"],
    "EIHOTEL": ["EIH Ltd.", "EIH Hotel", "EIHOTEL"],
    "EICHERMOT": ["Eicher Motors Ltd.", "Eicher Motors", "Eicher", "EICHERMOT"],
    "ELECON": ["Elecon Engineering Co. Ltd.", "Elecon Engineering", "Elecon"],
    "ELGIEQUIP": ["Elgi Equipments Ltd.", "Elgi Equipments", "ELGIEQUIP"],
    "EMAMILTD": ["Emami Ltd.", "Emami", "EMAMILTD"],
    "EMCURE": ["Emcure Pharmaceuticals Ltd.", "Emcure Pharma", "Emcure", "EMCURE"],
    "ENDURANCE": ["Endurance Technologies Ltd.", "Endurance Technologies", "Endurance", "ENDURANCE"],
    "ENGINERSIN": ["Engineers India Ltd.", "Engineers India", "ENGINERSIN"],
    "ERIS": ["Eris Lifesciences Ltd.", "Eris Lifesciences", "ERIS"],
    "ESCORTS": ["Escorts Kubota Ltd.", "Escorts Kubota", "Escorts", "ESCORTS"],
    "ETERNAL": ["Eternal Ltd.", "Eternal", "ETERNAL"],
    "EXIDEIND": ["Exide Industries Ltd.", "Exide Industries", "Exide", "EXIDEIND"],
    "NYKAA": ["FSN E-Commerce Ventures Ltd.", "FSN E-Commerce", "Nykaa", "NYKAA"],
    "FEDERALBNK": ["Federal Bank Ltd.", "Federal Bank", "Federal", "FEDERALBNK"],
    "FACT": ["Fertilisers and Chemicals Travancore Ltd.", "Fertilisers Travancore", "FACT"],
    "FINCABLES": ["Finolex Cables Ltd.", "Finolex Cables", "Finolex", "FINCABLES"],
    "FINPIPE": ["Finolex Industries Ltd.", "Finolex Industries", "Finolex", "FINPIPE"],
    "FSL": ["Firstsource Solutions Ltd.", "Firstsource Solutions", "Firstsource", "FSL"],
    "FIVESTAR": ["Five-Star Business Finance Ltd.", "Five-Star Business", "Five-Star", "FIVESTAR"],
    "FORTIS": ["Fortis Healthcare Ltd.", "Fortis Healthcare", "Fortis", "FORTIS"],
    "GAIL": ["GAIL (India) Ltd.", "GAIL India", "GAIL"],
    "GVT&D": ["GE Vernova T&D India Ltd.", "GE Vernova", "Vernova", "GVT&D"],
    "GMRAIRPORT": ["GMR Airports Ltd.", "GMR Airports", "GMR", "GMRAIRPORT"],
    "GRSE": ["Garden Reach Shipbuilders & Engineers Ltd.", "Garden Reach", "GRSE"],
    "GICRE": ["General Insurance Corporation of India", "General Insurance", "GICRE"],
    "GILLETTE": ["Gillette India Ltd.", "Gillette India", "Gillette", "GILLETTE"],
    "GLAND": ["Gland Pharma Ltd.", "Gland Pharma", "Gland", "GLAND"],
    "GLAXO": ["Glaxosmithkline Pharmaceuticals Ltd.", "Glaxosmithkline", "Glaxo", "GLAXO"],
    "MEDANTA": ["Global Health Ltd.", "Global Health", "Medanta", "MEDANTA"],
    "GODIGIT": ["Go Digit General Insurance Ltd.", "Go Digit", "GODIGIT"],
    "GPIL": ["Godawari Power & Ispat Ltd.", "Godawari Power", "Godawari", "GPIL"],
    "GODFRYPHLP": ["Godfrey Phillips India Ltd.", "Godfrey Phillips", "Godfrey", "GODFRYPHLP"],
    "GODREJAGRO": ["Godrej Agrovet Ltd.", "Godrej Agrovet", "Godrej", "GODREJAGRO"],
    "GODREJCP": ["Godrej Consumer Products Ltd.", "Godrej Consumer", "Godrej", "GODREJCP"],
    "GODREJIND": ["Godrej Industries Ltd.", "Godrej Industries", "Godrej", "GODREJIND"],
    "GODREJPROP": ["Godrej Properties Ltd.", "Godrej Properties", "Godrej", "GODREJPROP"],
    "GRANULES": ["Granules India Ltd.", "Granules India", "Granules", "GRANULES"],
    "GRAPHITE": ["Graphite India Ltd.", "Graphite India", "Graphite", "GRAPHITE"],
    "GRASIM": ["Grasim Industries Ltd.", "Grasim Industries", "Grasim", "GRASIM"],
    "GRAVITA": ["Gravita India Ltd.", "Gravita India", "Gravita", "GRAVITA"],
    "GESHIP": ["Great Eastern Shipping Co. Ltd.", "Great Eastern Shipping", "GESHIP"],
    "FLUOROCHEM": ["Gujarat Fluorochemicals Ltd.", "Gujarat Fluorochemicals", "Fluorochem", "FLUOROCHEM"],
    "GUJGASLTD": ["Gujarat Gas Ltd.", "Gujarat Gas", "Guj Gas", "GUJGASLTD"],
    "GMDCLTD": ["Gujarat Mineral Development Corporation Ltd.", "Gujarat Mineral", "GMDC", "GMDCLTD"],
    "GNFC": ["Gujarat Narmada Valley Fertilizers and Chemicals Ltd.", "Gujarat Narmada", "GNFC"],
    "GPPL": ["Gujarat Pipavav Port Ltd.", "Gujarat Pipavav", "Pipavav", "GPPL"],
    "GSPL": ["Gujarat State Petronet Ltd.", "Gujarat State Petronet", "GSPL"],
    "HBLENGINE": ["HBL Engineering Ltd.", "HBL Engineering", "HBL", "HBLENGINE"],
    "HCLTECH": ["HCL Technologies Ltd.", "HCL Technologies", "HCL", "HCLTECH"],
    "HDFCAMC": ["HDFC Asset Management Company Ltd.", "HDFC AMC", "HDFC", "HDFCAMC"],
    "HDFCBANK": ["HDFC Bank Ltd.", "HDFC Bank", "HDFC", "HDFCBANK"],
    "HDFCLIFE": ["HDFC Life Insurance Company Ltd.", "HDFC Life", "HDFCLIFE"],
    "HFCL": ["HFCL Ltd.", "HFCL"],
    "HAPPSTMNDS": ["Happiest Minds Technologies Ltd.", "Happiest Minds", "Happiest", "HAPPSTMNDS"],
    "HATHWAY": ["Hathway Cable & Datacom Ltd.", "Hathway Cable", "Hathway", "HATHWAY"],
    "HAVELLS": ["Havells India Ltd.", "Havells India", "Havells", "HAVELLS"],
    "HEG": ["HEG Ltd.", "HEG"],
    "HEROMOTOCO": ["Hero MotoCorp Ltd.", "Hero MotoCorp", "Hero", "HEROMOTOCO"],
    "HESTERBIO": ["Hester Biosciences Ltd.", "Hester Biosciences", "Hester", "HESTERBIO"],
    "HEXAWARE": ["Hexaware Technologies Ltd.", "Hexaware Technologies", "Hexaware", "HEXAWARE"],
    "HIKAL": ["Hikal Ltd.", "Hikal", "HIKAL"],
    "HIMATSEIDE": ["Himatsingka Seide Ltd.", "Himatsingka Seide", "Himatsingka", "HIMATSEIDE"],
    "HINDALCO": ["Hindalco Industries Ltd.", "Hindalco Industries", "Hindalco", "HINDALCO"],
    "HINDPETRO": ["Hindustan Petroleum Corporation Ltd.", "Hindustan Petroleum", "HPCL", "HINDPETRO"],
    "HINDUNILVR": ["Hindustan Unilever Ltd.", "Hindustan Unilever", "HUL", "HINDUNILVR"],
    "HINDZINC": ["Hindustan Zinc Ltd.", "Hindustan Zinc", "HINDZINC"],
    "HONAUT": ["Honeywell Automation India Ltd.", "Honeywell Automation", "Honeywell", "HONAUT"],
    "HONASA": ["Honasa Consumer Ltd.", "Honasa Consumer", "Honasa", "HONASA"],
    "HOTELEELA": ["Hotel Leela Venture Ltd.", "Hotel Leela", "Leela", "HOTELEELA"],
    "HPL": ["HPL Electric & Power Ltd.", "HPL Electric", "HPL"],
    "HSCL": ["Himachal Steel Corporation Ltd.", "Himachal Steel", "HSCL"],
    "IBREALEST": ["Indiabulls Real Estate Ltd.", "Indiabulls Real Estate", "Indiabulls", "IBREALEST"],
    "IBULHSG": ["Indiabulls Housing Finance Ltd.", "Indiabulls Housing", "IBULHSG"],
    "IBVENTURES": ["Indiabulls Ventures Ltd.", "Indiabulls Ventures", "IBVENTURES"],
    "ICICIBANK": ["ICICI Bank Ltd.", "ICICI Bank", "ICICI", "ICICIBANK"],
    "ICICIGI": ["ICICI Lombard General Insurance Company Ltd.", "ICICI Lombard", "ICICIGI"],
    "ICICIPRULI": ["ICICI Prudential Life Insurance Company Ltd.", "ICICI Prudential", "ICICIPRULI"],
    "IDBI": ["IDBI Bank Ltd.", "IDBI Bank", "IDBI"],
    "IDEA": ["Vodafone Idea Ltd.", "Vodafone Idea", "Idea", "IDEA"],
    "IDFC": ["IDFC Ltd.", "IDFC"],
    "IDFCFIRSTB": ["IDFC First Bank Ltd.", "IDFC First Bank", "IDFCFIRSTB"],
    "IFCI": ["IFCI Ltd.", "IFCI"],
    "IFBIND": ["IFB Industries Ltd.", "IFB Industries", "IFB", "IFBIND"],
    "IGL": ["Indraprastha Gas Ltd.", "Indraprastha Gas", "IGL"],
    "IIFL": ["IIFL Finance Ltd.", "IIFL Finance", "IIFL"],
    "IIFLSEC": ["IIFL Securities Ltd.", "IIFL Securities", "IIFLSEC"],
    "IMFA": ["Indian Metals & Ferro Alloys Ltd.", "Indian Metals", "IMFA"],
    "INDHOTEL": ["Indian Hotels Company Ltd.", "Indian Hotels", "Taj Hotels", "INDHOTEL"],
    "INDIACEM": ["India Cements Ltd.", "India Cements", "INDIACEM"],
    "INDIAGLYCO": ["India Glycols Ltd.", "India Glycols", "INDIAGLYCO"],
    "INDIAMART": ["IndiaMART InterMESH Ltd.", "IndiaMART", "INDIAMART"],
    "INDIANB": ["Indian Bank", "Indian Bank", "INDIANB"],
    "INDIANHUME": ["Indian Hume Pipe Co. Ltd.", "Indian Hume Pipe", "INDIANHUME"],
    "INDIGO": ["InterGlobe Aviation Ltd.", "InterGlobe Aviation", "IndiGo", "INDIGO"],
    "INDIGOPNTS": ["Indigo Paints Ltd.", "Indigo Paints", "INDIGOPNTS"],
    "INDLMETER": ["IMP Powers Ltd.", "IMP Powers", "INDLMETER"],
    "INDNIPPON": ["India Nippon Electricals Ltd.", "India Nippon", "INDNIPPON"],
    "INDOCO": ["Indoco Remedies Ltd.", "Indoco Remedies", "INDOCO"],
    "INDORAMA": ["Indo Rama Synthetics (India) Ltd.", "Indo Rama", "INDORAMA"],
    "INDOSTAR": ["IndoStar Capital Finance Ltd.", "IndoStar Capital", "INDOSTAR"],
    "INDOTECH": ["Indo Tech Transformers Ltd.", "Indo Tech", "INDOTECH"],
    "INDOTHAI": ["Indo Thai Securities Ltd.", "Indo Thai", "INDOTHAI"],
    "INDOWIND": ["Indowind Energy Ltd.", "Indowind Energy", "INDOWIND"],
    "INDUSINDBK": ["IndusInd Bank Ltd.", "IndusInd Bank", "IndusInd", "INDUSINDBK"],
    "INDUSTOWER": ["Indus Towers Ltd.", "Indus Towers", "INDUSTOWER"],
    "INFIBEAM": ["Infibeam Avenues Ltd.", "Infibeam Avenues", "INFIBEAM"],
    "INFOBEAN": ["InfoBeans Technologies Ltd.", "InfoBeans", "INFOBEAN"],
    "INFOMEDIA": ["Infomedia Press Ltd.", "Infomedia Press", "INFOMEDIA"],
    "INFOSYS": ["Infosys Ltd.", "Infosys", "INFY"],
    "INGERRAND": ["Ingersoll Rand (India) Ltd.", "Ingersoll Rand", "INGERRAND"],
    "INOXGREEN": ["Inox Green Energy Services Ltd.", "Inox Green", "INOXGREEN"],
    "INOXINDIA": ["INOX India Ltd.", "INOX India", "INOX"],
    "INOXWIND": ["Inox Wind Ltd.", "Inox Wind", "INOXWIND"],
    "INSECTICID": ["Insecticides (India) Ltd.", "Insecticides India", "INSECTICID"],
    "INTELLECT": ["Intellect Design Arena Ltd.", "Intellect Design", "Intellect", "INTELLECT"],
    "IOB": ["Indian Overseas Bank", "Indian Overseas Bank", "IOB"],
    "IOC": ["Indian Oil Corporation Ltd.", "Indian Oil", "IOC"],
    "IOLCP": ["IOL Chemicals and Pharmaceuticals Ltd.", "IOL Chemicals", "IOLCP"],
    "IPCA": ["Ipca Laboratories Ltd.", "Ipca Labs", "Ipca", "IPCA"],
    "IPCALAB": ["Ipca Laboratories Ltd.", "Ipca Labs", "Ipca", "IPCALAB"],
    "IRB": ["IRB Infrastructure Developers Ltd.", "IRB Infrastructure", "IRB"],
    "IRCON": ["IRCON International Ltd.", "IRCON International", "IRCON"],
    "IRCTC": ["Indian Railway Catering and Tourism Corporation Ltd.", "IRCTC"],
    "IRFC": ["Indian Railway Finance Corporation Ltd.", "Indian Railway Finance", "IRFC"],
    "ISEC": ["ICICI Securities Ltd.", "ICICI Securities", "ISEC"],
    "ITC": ["ITC Ltd.", "ITC"],
    "ITDC": ["India Tourism Development Corporation Ltd.", "India Tourism", "ITDC"],
    "ITI": ["ITI Ltd.", "ITI"],
    "IVC": ["IL&FS Investment Managers Ltd.", "IL&FS Investment", "IVC"],
    "IZMO": ["IZMO Ltd.", "IZMO"],
    "J&KBANK": ["Jammu & Kashmir Bank Ltd.", "J&K Bank", "JKBANK"],
    "JAGRAN": ["Jagran Prakashan Ltd.", "Jagran Prakashan", "JAGRAN"],
    "JAGSNPHARM": ["Jagsonpal Pharmaceuticals Ltd.", "Jagsonpal Pharma", "JAGSNPHARM"],
    "JAICORPLTD": ["Jai Corp Ltd.", "Jai Corp", "JAICORPLTD"],
    "JAMNAAUTO": ["Jamna Auto Industries Ltd.", "Jamna Auto", "JAMNAAUTO"],
    "JAYAGROGN": ["Jayant Agro-Organics Ltd.", "Jayant Agro", "JAYAGROGN"],
    "JAYBARMARU": ["Jay Bharat Maruti Ltd.", "Jay Bharat Maruti", "JAYBARMARU"],
    "JAYNECOIND": ["Jayaswal Neco Industries Ltd.", "Jayaswal Neco", "JAYNECOIND"],
    "JBCHEPHARM": ["J.B. Chemicals & Pharmaceuticals Ltd.", "J.B. Chemicals", "JB Pharma", "JBCHEPHARM"],
    "JCHAC": ["Johnson Controls-Hitachi Air Conditioning India Ltd.", "Johnson Controls-Hitachi", "JCHAC"],
    "JINDALPOLY": ["Jindal Poly Films Ltd.", "Jindal Poly Films", "JINDALPOLY"],
    "JINDALSAW": ["Jindal Saw Ltd.", "Jindal Saw", "JINDALSAW"],
    "JINDALSTEL": ["Jindal Steel & Power Ltd.", "Jindal Steel", "JSPL", "JINDALSTEL"],
    "JISLJALEQS": ["Jain Irrigation Systems Ltd.", "Jain Irrigation", "JISLJALEQS"],
    "JKCEMENT": ["JK Cement Ltd.", "JK Cement", "JKCEMENT"],
    "JKLAKSHMI": ["JK Lakshmi Cement Ltd.", "JK Lakshmi Cement", "JKLAKSHMI"],
    "JKPAPER": ["JK Paper Ltd.", "JK Paper", "JKPAPER"],
    "JKTYRE": ["JK Tyre & Industries Ltd.", "JK Tyre", "JKTYRE"],
    "JMFINANCIL": ["JM Financial Ltd.", "JM Financial", "JMFINANCIL"],
    "JOCIL": ["Jocil Ltd.", "Jocil", "JOCIL"],
    "JPASSOCIAT": ["Jaiprakash Associates Ltd.", "Jaiprakash Associates", "JPASSOCIAT"],
    "JPOLYINVST": ["Jindal Poly Investment and Finance Company Ltd.", "Jindal Poly Investment", "JPOLYINVST"],
    "JPPOWER": ["Jaiprakash Power Ventures Ltd.", "Jaiprakash Power", "JPPOWER"],
    "JSL": ["Jindal Stainless Ltd.", "Jindal Stainless", "JSL"],
    "JSWENERGY": ["JSW Energy Ltd.", "JSW Energy", "JSWENERGY"],
    "JSWINFRA": ["JSW Infrastructure Ltd.", "JSW Infrastructure", "JSWINFRA"],
    "JSWSTEEL": ["JSW Steel Ltd.", "JSW Steel", "JSWSTEEL"],
    "JUBLFOOD": ["Jubilant FoodWorks Ltd.", "Jubilant FoodWorks", "JUBLFOOD"],
    "JUBLINDS": ["Jubilant Industries Ltd.", "Jubilant Industries", "JUBLINDS"],
    "JUBLINGREA": ["Jubilant Ingrevia Ltd.", "Jubilant Ingrevia", "JUBLINGREA"],
    "JUBLPHARMA": ["Jubilant Pharmova Ltd.", "Jubilant Pharmova", "JUBLPHARMA"],
    "JUSTDIAL": ["Just Dial Ltd.", "Just Dial", "JUSTDIAL"],
    "JWL": ["Jupiter Wagons Ltd.", "Jupiter Wagons", "JWL"],
    "KABRAEXTRU": ["Kabra Extrusion Technik Ltd.", "Kabra Extrusion", "KABRAEXTRU"],
    "KAJARIACER": ["Kajaria Ceramics Ltd.", "Kajaria Ceramics", "KAJARIACER"],
    "KALPATPOWR": ["Kalpataru Power Transmission Ltd.", "Kalpataru Power", "KALPATPOWR"],
    "KALYANKJIL": ["Kalyan Jewellers India Ltd.", "Kalyan Jewellers", "KALYANKJIL"],
    "KAMATHOTEL": ["Kamat Hotels (I) Ltd.", "Kamat Hotels", "KAMATHOTEL"],
    "KANSAINER": ["Kansai Nerolac Paints Ltd.", "Kansai Nerolac", "KANSAINER"],
    "KARURVYSYA": ["Karur Vysya Bank Ltd.", "Karur Vysya Bank", "KARURVYSYA"],
    "KAYNES": ["Kaynes Technology India Ltd.", "Kaynes Technology", "KAYNES"],
    "KCP": ["KCP Ltd.", "KCP"],
    "KCPSUGIND": ["KCP Sugar and Industries Corporation Ltd.", "KCP Sugar", "KCPSUGIND"],
    "KEC": ["KEC International Ltd.", "KEC International", "KEC"],
    "KECL": ["Kirloskar Electric Company Ltd.", "Kirloskar Electric", "KECL"],
    "KEI": ["KEI Industries Ltd.", "KEI Industries", "KEI"],
    "KESORAMIND": ["Kesoram Industries Ltd.", "Kesoram Industries", "KESORAMIND"],
    "KEYFINSERV": ["Keynote Financial Services Ltd.", "Keynote Financial", "KEYFINSERV"],
    "KFINTECH": ["Kfin Technologies Ltd.", "Kfin Technologies", "KFINTECH"],
    "KGL": ["Karuturi Global Ltd.", "Karuturi Global", "KGL"],
    "KHADIM": ["Khadim India Ltd.", "Khadim India", "KHADIM"],
    "KIMS": ["Krishna Institute of Medical Sciences Ltd.", "KIMS", "Krishna Institute"],
    "KINGFA": ["Kingfa Science & Technology (India) Ltd.", "Kingfa Science", "KINGFA"],
    "KIOCL": ["KIOCL Ltd.", "KIOCL"],
    "KIRIINDUS": ["Kiri Industries Ltd.", "Kiri Industries", "KIRIINDUS"],
    "KIRLOSBROS": ["Kirloskar Brothers Ltd.", "Kirloskar Brothers", "KIRLOSBROS"],
    "KIRLOSENG": ["Kirloskar Oil Engines Ltd.", "Kirloskar Oil Engines", "KIRLOSENG"],
    "KIRLOSIND": ["Kirloskar Industries Ltd.", "Kirloskar Industries", "KIRLOSIND"],
    "KITEX": ["Kitex Garments Ltd.", "Kitex Garments", "KITEX"],
    "KKCL": ["Kewal Kiran Clothing Ltd.", "Kewal Kiran", "KKCL"],
    "KMSUGAR": ["KM Sugar Mills Ltd.", "KM Sugar Mills", "KMSUGAR"],
    "KNRCON": ["KNR Constructions Ltd.", "KNR Constructions", "KNRCON"],
    "KOPRAN": ["Kopran Ltd.", "Kopran", "KOPRAN"],
    "KOTAKBANK": ["Kotak Mahindra Bank Ltd.", "Kotak Mahindra Bank", "Kotak Bank", "KOTAKBANK"],
    "KOTARISUG": ["Kothari Sugars & Chemicals Ltd.", "Kothari Sugars", "KOTARISUG"],
    "KOTYARK": ["Kotyark Industries Ltd.", "Kotyark Industries", "KOTYARK"],
    "KPIGREEN": ["KPI Green Energy Ltd.", "KPI Green Energy", "KPIGREEN"],
    "KPRMILL": ["K.P.R. Mill Ltd.", "K.P.R. Mill", "KPRMILL"],
    "KRBL": ["KRBL Ltd.", "KRBL"],
    "KREBSBIO": ["Krebs Biochemicals and Industries Ltd.", "Krebs Biochemicals", "KREBSBIO"],
    "HAPPSTMNDS": ["Happiest Minds Technologies Ltd.", "Happiest Minds", "Happiest", "HAPPSTMNDS"],
     "LYPSAGEMS": ["Lypsa Gems & Jewellery Ltd.", "Lypsa Gems", "LYPSAGEMS"],
    "M&M": ["Mahindra & Mahindra Ltd.", "Mahindra & Mahindra", "Mahindra", "M&M"],
    "M&MFIN": ["Mahindra & Mahindra Financial Services Ltd.", "Mahindra Finance", "M&MFIN"],
    "MAANALU": ["Maan Aluminium Ltd.", "Maan Aluminium", "MAANALU"],
    "MACPOWER": ["Macpower CNC Machines Ltd.", "Macpower CNC", "MACPOWER"],
    "MADHAV": ["Madhav Marbles and Granites Ltd.", "Madhav Marbles", "MADHAV"],
    "MADRASFERT": ["Madras Fertilizers Ltd.", "Madras Fertilizers", "MADRASFERT"],
    "MAFANG": ["Mafatlal Industries Ltd.", "Mafatlal Industries", "MAFANG"],
    "MAGADSUGAR": ["Magadh Sugar & Energy Ltd.", "Magadh Sugar", "MAGADSUGAR"],
    "MAGNUM": ["Magnum Ventures Ltd.", "Magnum Ventures", "MAGNUM"],
    "MAHABANK": ["Bank of Maharashtra", "Bank of Maharashtra", "Mahabank", "MAHABANK"],
    "MAHAPEXLTD": ["Maha Rashtra Apex Corporation Ltd.", "Maha Rashtra Apex", "MAHAPEXLTD"],
    "MAHASTEEL": ["Mahamaya Steel Industries Ltd.", "Mahamaya Steel", "MAHASTEEL"],
    "MAHEPC": ["Mahindra EPC Irrigation Ltd.", "Mahindra EPC", "MAHEPC"],
    "MAHINDCIE": ["Mahindra CIE Automotive Ltd.", "Mahindra CIE", "MAHINDCIE"],
    "MAHLOG": ["Mahindra Logistics Ltd.", "Mahindra Logistics", "MAHLOG"],
    "MAHSCOOTER": ["Maharashtra Scooters Ltd.", "Maharashtra Scooters", "MAHSCOOTER"],
    "MAHSEAMLES": ["Maharashtra Seamless Ltd.", "Maharashtra Seamless", "MAHSEAMLES"],
    "MAITHANALL": ["Maithan Alloys Ltd.", "Maithan Alloys", "MAITHANALL"],
    "MAJESCO": ["Majesco Ltd.", "Majesco", "MAJESCO"],
    "MALUPAPER": ["Malu Paper Mills Ltd.", "Malu Paper", "MALUPAPER"],
    "MANAKALUCO": ["Manaksia Aluminium Company Ltd.", "Manaksia Aluminium", "MANAKALUCO"],
    "MANAKCOAT": ["Manaksia Coated Metals & Industries Ltd.", "Manaksia Coated", "MANAKCOAT"],
    "MANAKIND": ["Manaksia Industries Ltd.", "Manaksia Industries", "MANAKIND"],
    "MANAKSTEEL": ["Manaksia Steels Ltd.", "Manaksia Steels", "MANAKSTEEL"],
    "MANALIPETC": ["Manali Petrochemicals Ltd.", "Manali Petrochemicals", "MANALIPETC"],
    "MANAPPURAM": ["Manappuram Finance Ltd.", "Manappuram Finance", "MANAPPURAM"],
    "MANDHANA": ["Mandhana Retail Ventures Ltd.", "Mandhana Retail", "MANDHANA"],
    "MANGALAM": ["Mangalam Drugs & Organics Ltd.", "Mangalam Drugs", "MANGALAM"],
    "MANGCHEFER": ["Mangalore Chemicals & Fertilizers Ltd.", "Mangalore Chemicals", "MANGCHEFER"],
    "MANGLMCEM": ["Mangalam Cement Ltd.", "Mangalam Cement", "MANGLMCEM"],
    "MANINDS": ["Man Industries (India) Ltd.", "Man Industries", "MANINDS"],
    "MANINFRA": ["Man Infraconstruction Ltd.", "Man Infraconstruction", "MANINFRA"],
    "MANPASAND": ["Manpasand Beverages Ltd.", "Manpasand Beverages", "MANPASAND"],
    "MARALOVER": ["Maral Overseas Ltd.", "Maral Overseas", "MARALOVER"],
    "MARATHON": ["Marathon Nextgen Realty Ltd.", "Marathon Nextgen", "MARATHON"],
    "MARICO": ["Marico Ltd.", "Marico", "MARICO"],
    "MARKSANS": ["Marksans Pharma Ltd.", "Marksans Pharma", "MARKSANS"],
    "MARUTI": ["Maruti Suzuki India Ltd.", "Maruti Suzuki", "Maruti", "MARUTI"],
    "MASFIN": ["MAS Financial Services Ltd.", "MAS Financial", "MASFIN"],
    "MASTEK": ["Mastek Ltd.", "Mastek", "MASTEK"],
    "MAWANASUG": ["Mawana Sugars Ltd.", "Mawana Sugars", "MAWANASUG"],
    "MAXHEALTH": ["Max Healthcare Institute Ltd.", "Max Healthcare", "MAXHEALTH"],
    "MAXIND": ["Max India Ltd.", "Max India", "MAXIND"],
    "MAXVIL": ["Max Ventures and Industries Ltd.", "Max Ventures", "MAXVIL"],
    "MAYURUNIQ": ["Mayur Uniquoter Ltd.", "Mayur Uniquoter", "MAYURUNIQ"],
    "MAZDA": ["Mazda Ltd.", "Mazda", "MAZDA"],
    "MAZDOCK": ["Mazagon Dock Shipbuilders Ltd.", "Mazagon Dock", "MAZDOCK"],
    "MBAPL": ["Madhya Bharat Agro Products Ltd.", "Madhya Bharat Agro", "MBAPL"],
    "MBLINFRA": ["MBL Infrastructures Ltd.", "MBL Infrastructures", "MBLINFRA"],
    "MCDOWELL-N": ["United Spirits Ltd.", "United Spirits", "McDowell", "MCDOWELL-N"],
    "MCX": ["Multi Commodity Exchange of India Ltd.", "Multi Commodity Exchange", "MCX"],
    "METROPOLIS": ["Metropolis Healthcare Ltd.", "Metropolis Healthcare", "METROPOLIS"],
    "MFSL": ["Max Financial Services Ltd.", "Max Financial", "MFSL"],
    "MGL": ["Mahanagar Gas Ltd.", "Mahanagar Gas", "MGL"],
    "MHRIL": ["Mahindra Holidays & Resorts India Ltd.", "Mahindra Holidays", "MHRIL"],
    "MICEL": ["MIC Electronics Ltd.", "MIC Electronics", "MICEL"],
    "MIDHANI": ["Mishra Dhatu Nigam Ltd.", "Mishra Dhatu", "MIDHANI"],
    "MINDACORP": ["Minda Corporation Ltd.", "Minda Corporation", "MINDACORP"],
    "MINDAIND": ["Minda Industries Ltd.", "Minda Industries", "MINDAIND"],
    "MINDTREE": ["Mindtree Ltd.", "Mindtree", "MINDTREE"],
    "MIRCELECTR": ["MIRC Electronics Ltd.", "MIRC Electronics", "MIRCELECTR"],
    "MIRZAINT": ["Mirza International Ltd.", "Mirza International", "MIRZAINT"],
    "MMFL": ["MM Forgings Ltd.", "MM Forgings", "MMFL"],
    "MMTC": ["MMTC Ltd.", "MMTC"],
    "MOIL": ["MOIL Ltd.", "MOIL"],
    "MOL": ["Meghmani Organics Ltd.", "Meghmani Organics", "MOL"],
    "MOLDTECH": ["Mold-Tek Technologies Ltd.", "Mold-Tek Technologies", "MOLDTECH"],
    "MOLDTKPAC": ["Mold-Tek Packaging Ltd.", "Mold-Tek Packaging", "MOLDTKPAC"],
    "MONNETISPA": ["Monnet Ispat and Energy Ltd.", "Monnet Ispat", "MONNETISPA"],
    "MONTECARLO": ["Monte Carlo Fashions Ltd.", "Monte Carlo Fashions", "MONTECARLO"],
    "MORARJEE": ["Morarjee Textiles Ltd.", "Morarjee Textiles", "MORARJEE"],
    "MOREPENLAB": ["Morepen Laboratories Ltd.", "Morepen Laboratories", "MOREPENLAB"],
    "MOSCHIP": ["Moschip Semiconductor Technology Ltd.", "Moschip Semiconductor", "MOSCHIP"],
    "MOTILALOFS": ["Motilal Oswal Financial Services Ltd.", "Motilal Oswal", "MOTILALOFS"],
    "MPHASIS": ["Mphasis Ltd.", "Mphasis", "MPHASIS"],
    "MPSLTD": ["MPS Ltd.", "MPS"],
    "MRF": ["MRF Ltd.", "MRF"],
    "MRO-TEK": ["MRO-TEK Realty Ltd.", "MRO-TEK Realty", "MRO-TEK"],
    "MRPL": ["Mangalore Refinery and Petrochemicals Ltd.", "Mangalore Refinery", "MRPL"],
    "MSPL": ["MSP Steel & Power Ltd.", "MSP Steel", "MSPL"],
    "MTARTECH": ["MTAR Technologies Ltd.", "MTAR Technologies", "MTARTECH"],
    "MUKANDLTD": ["Mukand Ltd.", "Mukand", "MUKANDLTD"],
    "MUKTAARTS": ["Mukta Arts Ltd.", "Mukta Arts", "MUKTAARTS"],
    "MUNJALAU": ["Munjal Auto Industries Ltd.", "Munjal Auto", "MUNJALAU"],
    "MUNJALSHOW": ["Munjal Showa Ltd.", "Munjal Showa", "MUNJALSHOW"],
    "MURUDCERA": ["Murudeshwar Ceramics Ltd.", "Murudeshwar Ceramics", "MURUDCERA"],
    "MUTHOOTCAP": ["Muthoot Capital Services Ltd.", "Muthoot Capital", "MUTHOOTCAP"],
    "MUTHOOTFIN": ["Muthoot Finance Ltd.", "Muthoot Finance", "MUTHOOTFIN"],
    "NACLIND": ["NACL Industries Ltd.", "NACL Industries", "NACLIND"],
    "NAGAFERT": ["Nagarjuna Fertilizers and Chemicals Ltd.", "Nagarjuna Fertilizers", "NAGAFERT"],
    "NAGAROIL": ["Nagarjuna Oil Refinery Ltd.", "Nagarjuna Oil", "NAGAROIL"],
    "NAGREEKCAP": ["Nagreeka Capital & Infrastructure Ltd.", "Nagreeka Capital", "NAGREEKCAP"],
    "NAGREEKEXP": ["Nagreeka Exports Ltd.", "Nagreeka Exports", "NAGREEKEXP"],
    "NAHARINDUS": ["Nahar Industrial Enterprises Ltd.", "Nahar Industrial", "NAHARINDUS"],
    "NAHARPOLY": ["Nahar Poly Films Ltd.", "Nahar Poly Films", "NAHARPOLY"],
    "NAHARSPING": ["Nahar Spinning Mills Ltd.", "Nahar Spinning", "NAHARSPING"],
    "NAM-INDIA": ["Nippon Life India Asset Management Ltd.", "Nippon Life India AMC", "NAM-INDIA"],
    "NARMADA": ["Narmada Gelatines Ltd.", "Narmada Gelatines", "NARMADA"],
    "NATCOPHARM": ["Natco Pharma Ltd.", "Natco Pharma", "NATCOPHARM"],
    "NATHBIOGEN": ["Nath Bio-Genes (India) Ltd.", "Nath Bio-Genes", "NATHBIOGEN"],
    "NATIONALUM": ["National Aluminium Company Ltd.", "National Aluminium", "NALCO", "NATIONALUM"],
    "NAUKRI": ["Info Edge (India) Ltd.", "Info Edge", "NAUKRI"],
    "NAVA": ["Nava Bharat Ventures Ltd.", "Nava Bharat", "NAVA"],
    "NAVINFLUOR": ["Navin Fluorine International Ltd.", "Navin Fluorine", "NAVINFLUOR"],
    "NAVKARCORP": ["Navkar Corporation Ltd.", "Navkar Corporation", "NAVKARCORP"],
    "NAVNETEDUL": ["Navneet Education Ltd.", "Navneet Education", "NAVNETEDUL"],
    "NAZARA": ["Nazara Technologies Ltd.", "Nazara Technologies", "NAZARA"],
    "NBCC": ["NBCC (India) Ltd.", "NBCC India", "NBCC"],
    "NBIFIN": ["N.B.I. Industrial Finance Company Ltd.", "N.B.I. Industrial Finance", "NBIFIN"],
    "NCC": ["NCC Ltd.", "NCC"],
    "NCLIND": ["NCL Industries Ltd.", "NCL Industries", "NCLIND"],
    "NDL": ["Nandan Denim Ltd.", "Nandan Denim", "NDL"],
    "NDRAUTO": ["NDR Auto Components Ltd.", "NDR Auto", "NDRAUTO"],
    "NDTV": ["New Delhi Television Ltd.", "NDTV"],
    "NECCLTD": ["North Eastern Carrying Corporation Ltd.", "North Eastern Carrying", "NECCLTD"],
    "NELCAST": ["Nelcast Ltd.", "Nelcast", "NELCAST"],
    "NELCO": ["NELCO Ltd.", "NELCO"],
    "NEOGEN": ["Neogen Chemicals Ltd.", "Neogen Chemicals", "NEOGEN"],
    "NESCO": ["Nesco Ltd.", "Nesco", "NESCO"],
    "NESTLEIND": ["Nestle India Ltd.", "Nestle India", "Nestle", "NESTLEIND"],
    "NETWORK18": ["Network18 Media & Investments Ltd.", "Network18", "NETWORK18"],
    "NEULANDLAB": ["Neuland Laboratories Ltd.", "Neuland Laboratories", "NEULANDLAB"],
    "NEWGEN": ["Newgen Software Technologies Ltd.", "Newgen Software", "NEWGEN"],
    "NEXTMEDIA": ["Next Mediaworks Ltd.", "Next Mediaworks", "NEXTMEDIA"],
    "NFL": ["National Fertilizers Ltd.", "National Fertilizers", "NFL"],
    "NH": ["Narayana Hrudayalaya Ltd.", "Narayana Hrudayalaya", "NH"],
    "NHPC": ["NHPC Ltd.", "NHPC"],
    "NIACL": ["The New India Assurance Company Ltd.", "New India Assurance", "NIACL"],
    "NIBL": ["NRB Industrial Bearings Ltd.", "NRB Industrial", "NIBL"],
    "NICCO": ["Nicco Corporation Ltd.", "Nicco Corporation", "NICCO"],
    "NIITLTD": ["NIIT Ltd.", "NIIT", "NIITLTD"],
    "NILAINFRA": ["Nila Infrastructures Ltd.", "Nila Infrastructures", "NILAINFRA"],
    "NILKAMAL": ["Nilkamal Ltd.", "Nilkamal", "NILKAMAL"],
    "NIPPOBATRY": ["Indo-National Ltd.", "Indo-National", "NIPPOBATRY"],
    "NIRAJ": ["Niraj Cement Structurals Ltd.", "Niraj Cement", "NIRAJ"],
    "NITCO": ["Nitco Ltd.", "Nitco", "NITCO"],
    "NITINSPIN": ["Nitin Spinners Ltd.", "Nitin Spinners", "NITINSPIN"],
    "NLCINDIA": ["NLC India Ltd.", "NLC India", "NLCINDIA"],
    "NMDC": ["NMDC Ltd.", "NMDC"],
    "NOCIL": ["NOCIL Ltd.", "NOCIL"],
    "NOIDATOLL": ["Noida Toll Bridge Company Ltd.", "Noida Toll Bridge", "NOIDATOLL"],
    "NORBTEAEXP": ["Norben Tea & Exports Ltd.", "Norben Tea", "NORBTEAEXP"],
    "NOVARTIND": ["Novartis India Ltd.", "Novartis India", "NOVARTIND"],
    "NPBET": ["PNB Gilts Ltd.", "PNB Gilts", "NPBET"],
    "NRAIL": ["N R Agarwal Industries Ltd.", "N R Agarwal", "NRAIL"],
    "NRBBEARING": ["NRB Bearing Ltd.", "NRB Bearing", "NRBBEARING"],
    "NSIL": ["Nalwa Sons Investments Ltd.", "Nalwa Sons", "NSIL"],
    "NTPC": ["NTPC Ltd.", "NTPC"],
    "NUCLEUS": ["Nucleus Software Exports Ltd.", "Nucleus Software", "NUCLEUS"],
    "NURECA": ["Nureca Ltd.", "Nureca", "NURECA"],
    "NUVOCO": ["Nuvoco Vistas Corporation Ltd.", "Nuvoco Vistas", "NUVOCO"],
    "OBEROIRLTY": ["Oberoi Realty Ltd.", "Oberoi Realty", "OBEROIRLTY"],
    "OCCL": ["Oriental Carbon & Chemicals Ltd.", "Oriental Carbon", "OCCL"],
    "OFSS": ["Oracle Financial Services Software Ltd.", "Oracle Financial", "OFSS"],
    "OIL": ["Oil India Ltd.", "Oil India", "OIL"],
    "OILCOUNTUB": ["Oil Country Tubular Ltd.", "Oil Country Tubular", "OILCOUNTUB"],
    "OLECTRA": ["Olectra Greentech Ltd.", "Olectra Greentech", "OLECTRA"],
    "OMAXAUTO": ["Omax Autos Ltd.", "Omax Autos", "OMAXAUTO"],
    "OMAXE": ["Omaxe Ltd.", "Omaxe", "OMAXE"],
    "OMINFRAL": ["OM Infra Ltd.", "OM Infra", "OMINFRAL"],
    "ONELIFECAP": ["Onelife Capital Advisors Ltd.", "Onelife Capital", "ONELIFECAP"],
    "ONGC": ["Oil & Natural Gas Corporation Ltd.", "ONGC"],
    "ONMOBILE": ["OnMobile Global Ltd.", "OnMobile Global", "ONMOBILE"],
    "OPTIEMUS": ["Optiemus Infracom Ltd.", "Optiemus Infracom", "OPTIEMUS"],
    "ORBTEXP": ["Orbit Exports Ltd.", "Orbit Exports", "ORBTEXP"],
    "ORICONENT": ["Oricon Enterprises Ltd.", "Oricon Enterprises", "ORICONENT"],
    "ORIENTABRA": ["Orient Abrasives Ltd.", "Orient Abrasives", "ORIENTABRA"],
    "ORIENTALTL": ["Oriental Trimex Ltd.", "Oriental Trimex", "ORIENTALTL"],
    "ORIENTBELL": ["Orient Bell Ltd.", "Orient Bell", "ORIENTBELL"],
    "ORIENTCEM": ["Orient Cement Ltd.", "Orient Cement", "ORIENTCEM"],
    "ORIENTELEC": ["Orient Electric Ltd.", "Orient Electric", "ORIENTELEC"],
    "ORIENTHOT": ["Oriental Hotels Ltd.", "Oriental Hotels", "ORIENTHOT"],
    "ORIENTLTD": ["Orient Press Ltd.", "Orient Press", "ORIENTLTD"],
    "ORIENTPPR": ["Orient Paper & Industries Ltd.", "Orient Paper", "ORIENTPPR"],
    "ORISSAMINE": ["Orissa Minerals Development Company Ltd.", "Orissa Minerals", "ORISSAMINE"],
    "ORTEL": ["Ortel Communications Ltd.", "Ortel Communications", "ORTEL"],
    "OSIAHYPER": ["Osia Hyper Retail Ltd.", "Osia Hyper", "OSIAHYPER"],
    "OSWALAGRO": ["Oswal Agro Mills Ltd.", "Oswal Agro Mills", "OSWALAGRO"],
    "OSWALSEEDS": ["Oswal Seeds Ltd.", "Oswal Seeds", "OSWALSEEDS"],
    "PAGEIND": ["Page Industries Ltd.", "Page Industries", "PAGEIND"],
    "PAISALO": ["Paisalo Digital Ltd.", "Paisalo Digital", "PAISALO"],
    "PALREDTEC": ["Palred Technologies Ltd.", "Palred Technologies", "PALREDTEC"],
    "PANACEABIO": ["Panacea Biotec Ltd.", "Panacea Biotec", "PANACEABIO"],
    "PANAMAPET": ["Panama Petrochem Ltd.", "Panama Petrochem", "PANAMAPET"],
    "PANORAMUNI": ["Panoramic Universal Ltd.", "Panoramic Universal", "PANORAMUNI"],
    "PARACABLES": ["Paramount Communications Ltd.", "Paramount Communications", "PARACABLES"],
    "PARADEEP": ["Paradeep Phosphates Ltd.", "Paradeep Phosphates", "PARADEEP"],
    "PARAGMILK": ["Parag Milk Foods Ltd.", "Parag Milk Foods", "PARAGMILK"],
    "PARAS": ["Paras Defence and Space Technologies Ltd.", "Paras Defence", "PARAS"],
    "PARSVNATH": ["Parsvnath Developers Ltd.", "Parsvnath Developers", "PARSVNATH"],
    "PATANJALI": ["Patanjali Foods Ltd.", "Patanjali Foods", "PATANJALI"],
    "PATELENG": ["Patel Engineering Ltd.", "Patel Engineering", "PATELENG"],
    "PATINTLOG": ["Patel Integrated Logistics Ltd.", "Patel Integrated", "PATINTLOG"],
    "PCBL": ["PCBL Ltd.", "PCBL"],
    "PCJEWELLER": ["PC Jeweller Ltd.", "PC Jeweller", "PCJEWELLER"],
    "PDMJEPAPER": ["Pudumjee Paper Products Ltd.", "Pudumjee Paper", "PDMJEPAPER"],
    "PDSL": ["PDS Ltd.", "PDS"],
    "PEL": ["Piramal Enterprises Ltd.", "Piramal Enterprises", "PEL"],
    "PENIND": ["Pennar Industries Ltd.", "Pennar Industries", "PENIND"],
    "PERSISTENT": ["Persistent Systems Ltd.", "Persistent Systems", "PERSISTENT"],
    "PETRONET": ["Petronet LNG Ltd.", "Petronet LNG", "PETRONET"],
    "PFC": ["Power Finance Corporation Ltd.", "Power Finance", "PFC"],
    "PFIZER": ["Pfizer Ltd.", "Pfizer", "PFIZER"],
    "PFOCUS": ["Prime Focus Ltd.", "Prime Focus", "PFOCUS"],
    "PFS": ["PTC India Financial Services Ltd.", "PTC India Financial", "PFS"],
    "PGEL": ["PG Electroplast Ltd.", "PG Electroplast", "PGEL"],
    "PGHH": ["Procter & Gamble Hygiene and Health Care Ltd.", "P&G Hygiene", "PGHH"],
    "PGHL": ["Procter & Gamble Health Ltd.", "P&G Health", "PGHL"],
    "PGIL": ["Pearl Global Industries Ltd.", "Pearl Global", "PGIL"],
    "PHILIPCARB": ["Phillips Carbon Black Ltd.", "Phillips Carbon", "PHILIPCARB"],
    "PHOENIXLTD": ["The Phoenix Mills Ltd.", "Phoenix Mills", "PHOENIXLTD"],
    "PIDILITIND": ["Pidilite Industries Ltd.", "Pidilite Industries", "PIDILITIND"],
    "PIIND": ["PI Industries Ltd.", "PI Industries", "PIIND"],
    "PILANIINVS": ["Pilani Investment and Industries Corporation Ltd.", "Pilani Investment", "PILANIINVS"],
    "PILITA": ["Pil Italica Lifestyle Ltd.", "Pil Italica", "PILITA"],
    "PIONEEREMB": ["Pioneer Embroideries Ltd.", "Pioneer Embroideries", "PIONEEREMB"],
    "PIRAMAL": ["Piramal Enterprises Ltd.", "Piramal Enterprises", "PIRAMAL"],
    "PITTIENG": ["Pitti Engineering Ltd.", "Pitti Engineering", "PITTIENG"],
    "PLASTIBLEN": ["Plastiblends India Ltd.", "Plastiblends India", "PLASTIBLEN"],
    "PNB": ["Punjab National Bank", "Punjab National Bank", "PNB"],
    "PNBHOUSING": ["PNB Housing Finance Ltd.", "PNB Housing", "PNBHOUSING"],
    "PNCINFRA": ["PNC Infratech Ltd.", "PNC Infratech", "PNCINFRA"],
    "POCHIRAJU": ["Pochiraju Industries Ltd.", "Pochiraju Industries", "POCHIRAJU"],
    "PODDARMENT": ["Poddar Pigments Ltd.", "Poddar Pigments", "PODDARMENT"],
    "POKARNA": ["Pokarna Ltd.", "Pokarna", "POKARNA"],
    "POLICYBZR": ["PB Fintech Ltd.", "PB Fintech", "Policybazaar", "POLICYBZR"],
    "POLYCAB": ["Polycab India Ltd.", "Polycab India", "POLYCAB"],
    "POLYMED": ["Poly Medicure Ltd.", "Poly Medicure", "POLYMED"],
    "POLYPLEX": ["Polyplex Corporation Ltd.", "Polyplex Corporation", "POLYPLEX"],
    "PONNIERODE": ["Ponni Sugars (Erode) Ltd.", "Ponni Sugars", "PONNIERODE"],
    "POONAWALLA": ["Poonawalla Fincorp Ltd.", "Poonawalla Fincorp", "POONAWALLA"],
    "POWERGRID": ["Power Grid Corporation of India Ltd.", "Power Grid", "POWERGRID"],
    "POWERINDIA": ["Hitachi Energy India Ltd.", "Hitachi Energy", "POWERINDIA"],
    "PPL": ["Prakash Pipes Ltd.", "Prakash Pipes", "PPL"],
    "PPLPHARMA": ["Piramal Pharma Ltd.", "Piramal Pharma", "PPLPHARMA"],
    "PRABHAT": ["Prabhat Dairy Ltd.", "Prabhat Dairy", "PRABHAT"],
    "PRADIP": ["Pradip Overseas Ltd.", "Pradip Overseas", "PRADIP"],
    "PRAENG": ["Prajay Engineers Syndicate Ltd.", "Prajay Engineers", "PRAENG"],
    "PRAJIND": ["Praj Industries Ltd.", "Praj Industries", "PRAJIND"],
    "PRAKASH": ["Prakash Industries Ltd.", "Prakash Industries", "PRAKASH"],
    "PRAKASHCON": ["Prakash Constrowell Ltd.", "Prakash Constrowell", "PRAKASHCON"],
    "PRATIBHA": ["Pratibha Industries Ltd.", "Pratibha Industries", "PRATIBHA"],
    "PRECAM": ["Precision Camshafts Ltd.", "Precision Camshafts", "PRECAM"],
    "PRECOT": ["Precot Meridian Ltd.", "Precot Meridian", "PRECOT"],
    "PRECWIRE": ["Precision Wires India Ltd.", "Precision Wires", "PRECWIRE"],
    "PREMEXPLN": ["Premier Explosives Ltd.", "Premier Explosives", "PREMEXPLN"],
    "PREMIER": ["Premier Ltd.", "Premier", "PREMIER"],
    "PREMIERPOL": ["Premier Polyfilm Ltd.", "Premier Polyfilm", "PREMIERPOL"],
    "PRESSMN": ["Pressman Advertising Ltd.", "Pressman Advertising", "PRESSMN"],
    "PRESTIGE": ["Prestige Estates Projects Ltd.", "Prestige Estates", "PRESTIGE"],
    "PRICOLLTD": ["Pricol Ltd.", "Pricol", "PRICOLLTD"],
    "PRIMESECU": ["Prime Securities Ltd.", "Prime Securities", "PRIMESECU"],
    "PRINCEPIPE": ["Prince Pipes and Fittings Ltd.", "Prince Pipes", "PRINCEPIPE"],
    "PRITI": ["Priti International Ltd.", "Priti International", "PRITI"],
    "PRIVISCL": ["Privi Speciality Chemicals Ltd.", "Privi Speciality", "PRIVISCL"],
    "PROZONINTU": ["Prozone Intu Properties Ltd.", "Prozone Intu", "PROZONINTU"],
    "PSB": ["Punjab & Sind Bank", "Punjab & Sind Bank", "PSB"],
    "PSPPROJECT": ["PSP Projects Ltd.", "PSP Projects", "PSPPROJECT"],
    "PTC": ["PTC India Ltd.", "PTC India", "PTC"],
    "PTL": ["PTL Enterprises Ltd.", "PTL Enterprises", "PTL"],
    "PUNJABCHEM": ["Punjab Chemicals & Crop Protection Ltd.", "Punjab Chemicals", "PUNJABCHEM"],
    "PURVA": ["Puravankara Ltd.", "Puravankara", "PURVA"],
    "PVP": ["PVP Ventures Ltd.", "PVP Ventures", "PVP"],
    "PVR": ["PVR Ltd.", "PVR"]
}

# --- AUTO-GENERATED: Add missing COMPANY_SYMBOL_MAP entries from NSE500_COMPANIES ---

# Build a mapping from symbol to all its name variations from NSE500_COMPANIES
_symbol_to_names = defaultdict(list)
for i, entry in enumerate(NSE500_COMPANIES):
    if isinstance(entry, str) and entry.isupper() and len(entry) > 2 and (i == 0 or not NSE500_COMPANIES[i-1].isupper()):
        symbol = entry
        names = []
        j = i + 1
        while j < len(NSE500_COMPANIES) and not (isinstance(NSE500_COMPANIES[j], str) and NSE500_COMPANIES[j].isupper() and len(NSE500_COMPANIES[j]) > 2):
            names.append(NSE500_COMPANIES[j])
            j += 1
        if symbol not in COMPANY_SYMBOL_MAP:
            COMPANY_SYMBOL_MAP[symbol] = [symbol] + names

def get_company_symbol(company_name):
    """Get NSE stock symbol for a company name."""
    # Clean and normalize the company name
    clean_name = company_name.strip()
    
    # Try exact match first
    for symbol, names in COMPANY_SYMBOL_MAP.items():
        if clean_name in names:
            return symbol
    
    # Try case-insensitive match
    clean_name_lower = clean_name.lower()
    for symbol, names in COMPANY_SYMBOL_MAP.items():
        if any(clean_name_lower == name.lower() for name in names):
            return symbol
    
    # Try partial match
    for symbol, names in COMPANY_SYMBOL_MAP.items():
        if any(clean_name_lower in name.lower() or name.lower() in clean_name_lower for name in names):
            return symbol
    
    # If no match found, return Unknown
    return "Unknown"